### ISSUE TITLE
[BUG] Front needs to run on a specific node, receiving mails fails otherwise

### ISSUE THREAD

**Issue by technodrome** [Mailu/helm-charts#114]
**Describe the bug**
If the `front` container is not assigned to a specific node known upfront (e.g. using `nodeSelector` or affinity), it is impossible to forward ports and reach postfix. That means mails can be sent out, but not received.

The documentation does not clearly mention at all how should `front` container be deployed. The Helm chart contains `nodeSelector: {}` in `my-values-file.yaml`, however this would apply to the whole deployment which completely defeats the purpose of having random nodes spawn individual parts of Mailu based on the cluster's utilization.

**Environment**
K3s/K8s

## Questions
1. How are we supposed to deploy Mailu's `front` container? I had to resort to adding `nodeSelector` to `front` container only so that receiving mails works with ports being forwarded to its node on the firewall. This, however, is problematic because it means one component of the whole chart deployment **must** be deployed to e.g. master node and thus creates a clear dependency. If that node goes down with its `front` container, the whole mail service stack is gone.

2. Ports 80/443, thanks to their endpoint definition are reachable across all nodes (defined as endpoint). Is there any other way of having postfix listen through `front` even though `front` would be deployed on any node?

**Comment by technodrome** [comment]
Hi @micw, setting https://github.com/Mailu/helm-charts/pull/101 works. Setting `nodeSelector` works nicely. I will test setting up LoadBalancer next.

**Comment by arturhefczyc** [comment]
Would it solve the problem if the frontend was deployed on all nodes?
I guess, frontend does not use a lot of resources and such a redundancy would not be very costly but it might be a simple solution or at least a workaround.

**Comment by technodrome** [comment]
@arturhefczyc I think we should aim for a real solution here, not workarounds. Hence the LB solution is something we should be going for. If I manage that, I will contribute detailed documentation. Others with different setups should do, too, so that we cover as many proper real-life scenarios as possible without resorting to workarounds.

**Comment by micw** [comment]
We have a confirmed-to-work setup with k3s and klipper-lb (a small tweak was required, added externalTrafficPolicy = Local): https://github.com/Mailu/helm-charts/pull/84#issuecomment-963558110

Sould be the same with metal-lb (but I wait for a confirmation before I add it to the readme).

**Comment by technodrome** [comment]
I can confirm LB with Klipper works using latest Mailu Helm chart. Deployed tonight and pods are up. Will contribute documentation if needed, closing this ticket.
