### ISSUE TITLE
Add extra volume mapping for fetchmail (See #2049)

### ISSUE THREAD

**Issue by Diman0** [Mailu/helm-charts#122]
See the merged [PR#2049](https://github.com/Mailu/Mailu/pull/2049).
For persistence of fetchmail a new volume mapping is introduced. For docker-compose deployment the internal location /data is mapped to /{root}/data/fetchmail/. E.g. /mailu/data/fetchmail

The helm-chart must be updated to map /{root}/data/fetchmail to /data in the fetchmail image.

**Comment by fastlorenzo** [comment]
Possible in release 1.0.0
