### ISSUE TITLE
hostNetwork enablement for front.yaml deployment

### ISSUE THREAD

**Issue by cipianpascu** [Mailu/helm-charts#126]
Hi guys,

I struggled a lot to deploy mailu with the hostPort feature enabled. However, for some reason, this feature doesn't work. Maybe my kubernetes configuration doesn't allow it.
For this reason, I propose to enable the alternative with **hostNetwork** flag.

Thank you,
Ciprian

**Comment by micw** [comment]
Hello,
most security in mailu is IP based. hostNetwork would introduce several kinds of issues. There are multiple working options to expose mailu to the internet (e.g. using external LB).

I'm strictly against adding hostNetwork as a fix for your broken K8S setup in this chart. There's still the option to change the chart yourself if you really need it but I'd recommend to check why the other options are not working in your setup.

Kind regards,
Michael.
