### ISSUE TITLE
[BUG] POSTMASTER environment variable is not set

### ISSUE THREAD

**Issue by Diman0** [Mailu/helm-charts#127]
**Describe the bug**
The environment variable POSTMASTER should be available for the services:
- Admin
- Front
- Dovecot

See the [configuration reference](https://mailu.io/1.8/configuration.html#common-configuration) for a description of the env variable. 
If you use let's encrypt (ingress.tlsFlavor=letsencrypt), then Mailu will fail to start. See https://matrix.to/#/!RJFCFtixHgPhzacdhW:tedomum.net/$1638524324429112oalFq:matrix.org?via=tedomum.net&via=matrix.org&via=autonomic.zone

Currently only Dovecot has a static value configured. 

I think this variable must be defined under env: in
https://github.com/Mailu/helm-charts/blob/master/mailu/templates/front.yaml
https://github.com/Mailu/helm-charts/blob/master/mailu/templates/admin.yaml
https://github.com/Mailu/helm-charts/blob/master/mailu/templates/dovecot.yaml

and added to https://github.com/Mailu/helm-charts/blob/master/mailu/helm-lint-values.yaml so you can configure it.

**Comment by micw** [comment]
Confirmed and fixed. I also added $DOMAIN to front which is required at the same place
