### ISSUE TITLE
[BUG] New installation cannot run - missing resources

### ISSUE THREAD

**Issue by larsskj** [Mailu/helm-charts#128]
My mailserver crashed. For good - it was a very old tried and trusted host, and the only thing left on the host was mail, everything else had been migrated to Kubernetes.

For a long time I had wanted to move to Mailu, but I didn't find the project mature enough to do it. I do remember early attempts from the project running as a Daemon Set on all available nodes.

But the server was gone, probably the CPU has given up life. So I decided to give it a go to get something up and running in a hurry. I haven't regretted that yet - my Mailu is running in my cluster now and handling all mail. And I like it.

My cluster is a grownup mini-cluster running some midsized websites, and a lot of internal services like home automation. It's basically built on three PCs running Ubuntu Server 20.04 LTS with Core i7 and 32 GB RAM on each node. The nodes also runs a MariaDB Galera cluster - used for Mailu - and a GlusterFS/Heketi filesystem, used for Mailu as well.

It connects to the outside world using a 1 GB/s fiberlink. Basic mailservices are running on a loadbalancer created using MetalLB, and HTTP services are proxied using a combination of Træfik and HA Proxy. I have an ordinary firewall in front of all this.

I'm providing this information to indicate that I have a production setup running in a cluster where I'm willing to do experiments.

Now for the bug: The initial user experience wasn't very positive - Mailu started, you could login to the browser UIs, but you couldn't even send a mail from one internal user to another internal user in the same account.

It appeared that Spamd failed to start: The Helm chart only limits memory to 200Mi and CPU to 200m, and that's too little. I raised it to 500Mi/500m and things started to work.

However, after some days of running, I've noticed that ClamAV continues crashing and restarting - again, with OOM errors. I raised memory limits from 2Gi to 3Gi, and now it appears to run smoothly.

I'm running the latest version as of writing, 1.8.

If you want so, I can create a PR with my modifications.

**Comment by fastlorenzo** [comment]
Release 1.0.0 offers the possibility to fine tune each component of Mailu, this should give enough flexibility to run on low power devices.
