### ISSUE TITLE
Upgrade for Mailu 1.9

### ISSUE THREAD

**Issue by DerKnerd** [Mailu/helm-charts#131]
**Is your feature request related to a problem? Please describe.**
I would like to upgrade my Kubernetes hosted Mailu instance to 1.9 using the helm chart. If I try that, I only get errors in the web interfaces.

**Describe the solution you'd like**
An updated chart for 1.9.

**Describe alternatives you've considered**
I thought about creating a kustomization based installation but I would much prefer the Helm chart.

**Comment by micw** [comment]
Hello,

please give https://github.com/Mailu/helm-charts/tree/feature/1.9-fixes a try. I started this before the 1.9 release but stumbled across some issues in 1.9 that should be fixed meanwhile. In the branch I collected several 1.9 related PRs and suggestions.

**Comment by DerKnerd** [comment]
How do I apply a branch using Helm? I usually use Kustomization for deployments.

**Comment by micw** [comment]
You need to check out from github. If you need to create yamls from it to use with kustomize, have a look at https://github.com/Mailu/helm-charts/blob/master/pack_chart.sh#L79-L83

**Comment by DerKnerd** [comment]
I followed the script and managed to switch the helm install over to a kustomization based deployment. Thank you.

**Comment by technodrome** [comment]
That branch seems to be gone. Is it neccessary to have this ticket open, or is there a 1.9-related tracking ticket somewhere?

**Comment by DerKnerd** [comment]
Looks like the branch was merged. I will close this issue.
