### ISSUE TITLE
Bug: Ingress depreciated APIs - cannot deploy chart

### ISSUE THREAD

**Issue by caesarcxiv** [Mailu/helm-charts#134]
Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"

On K8 v1.22.5

**Comment by micw** [comment]
Which chart version? It should be fixed since months:
https://github.com/Mailu/helm-charts/commit/029ceb72a60f5976f94edf20a5efb7e8b1aff3a5

**Comment by caesarcxiv** [comment]
I needed to run, and then upgrade the chart
helm mapkubeapis mailu --namespace mailu
