### ISSUE TITLE
Failure to install mailu using helm chart

### ISSUE THREAD

**Issue by ananthunair** [Mailu/helm-charts#14]
I am trying to install the latest mailu chart into a minikube cluster. I have used the default `values.yaml` and  and added extra config values required for my setup. But the templating itself fails for the current chart.

On doing helm lint on the current chart (after cloning) i get the following error
```
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: mailu/templates/rspamd.yaml:26:25: executing "mailu/templates/rspamd.yaml" at <.Values.rspamd.image.repository>: nil pointer evaluating interface {}.image

Error: 1 chart(s) linted, 1 chart(s) failed
```

I am using `helm version`

`version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`

I suspected if it was a helm version issue, so tried this against v3.0.1 and v2.16.0. Still getting the same error. Wanted to if i am missing anything here.

**Comment by ananthunair** [comment]
@micw

**Comment by ananthunair** [comment]
**UPDATE:**

I figured out the problem. While un-commenting few values in the `values.yaml`, didn't realize the extra space in front them and helm being helm was showing error in a unrelated place all together. 
So the chart seems good. Apologies for the unneeded Issue opening.

I will be raising a PR to get rid of the unwanted space in-front of few commented out values so that the experience can be a bit more smoother.

Thanks

**Comment by micw** [comment]
@ananthunair I'm about to fix the lint errors to make error messages cleaner
