### ISSUE TITLE
Document external_relay.*

### ISSUE THREAD

**Issue by micw** [Mailu/helm-charts#140]
From values.yaml:

```
external_relay: {}
#    host: "[domain.tld]:port"
#    username: username
#    password: SECRET
#    # username and password can also be stored as secret:
#    secretName: external-relay-secret
#    usernameKey: username
#    passwordKey: password
```

This should be added to the README.

**Comment by fastlorenzo** [comment]
Added in README:

| Name                                       | Description                                                                                                                            | Value                                                                                            |
| ------------------------------------------ | -------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------ |
| `externalRelay.host`                       | Hostname of the external relay                                                                                                         | `""`                                                                                             |
| `externalRelay.username`                   | Username for the external relay                                                                                                        | `""`                                                                                             |
| `externalRelay.password`                   | Password for the external relay                                                                                                        | `""`                                                                                             |
| `externalRelay.existingSecret`             | Name of the secret containing the username and password for the external relay; if set, username and password will be ignored          | `""`                                                                                             |
| `externalRelay.usernameKey`                | Key in the secret containing the username for the external relay                                                                       | `relay-username`                                                                                 |
| `externalRelay.passwordKey`                | Key in the secret containing the password for the external relay                                                                       | `relay-password`                                                                                 |
| `externalRelay.networks`                   | List of networks that are allowed to use Mailu as external relay                                                                       | `[]`                                                                                             |
