### ISSUE TITLE
Support new RATELIMIT features

### ISSUE THREAD

**Issue by micw** [Mailu/helm-charts#149]
AUTH_RATELIMIT is now AUTH_RATELIMIT_IP and should be renamed.
AUTH_RATELIMIT_SUBNET is replaced by AUTH_RATELIMIT_EXEMPTION

The new chart should fail if any of the old settings are in use.

The following new settings should be added: AUTH_RATELIMIT_USER, AUTH_RATELIMIT_EXEMPTION_LENGTH

**Comment by fastlorenzo** [comment]
Done in #193

https://github.com/Mailu/helm-charts/blob/c2f739a9dfb17e9086eb44fe6816822a641e6918/mailu/values.yaml#L99-L123
