### ISSUE TITLE
Support advanced settings of mailu 1.9

### ISSUE THREAD

**Issue by micw** [Mailu/helm-charts#152]
Support and document:
* CREDENTIAL_ROUNDS 
* SESSION_COOKIE_SECURE 
* SESSION_TIMEOUT 
* PERMANENT_SESSION_LIFETIME
* LETSENCRYPT_SHORTCHAIN

**Comment by woj-tek** [comment]
I assume those should be included in admin template (i.e. https://github.com/Mailu/helm-charts/blob/master/mailu/templates/admin.yaml)?

Are there any preferences regarding scope/prefix? E.g. `advanced.credentialRounds` or `admin.credentialRounds`?

**Comment by micw** [comment]
I'd say just `admin.credentialRounds`. They should be ommited if no value given in values.yaml.

**Comment by woj-tek** [comment]
Created #190 - I hope it's ok. Included variables in the initial file but commented out (like other optional configs), ability to set true/false (so force disable something) by using `hasKey`).

Idea reformatted table with parameters and wasn't sure it would be fine but I think source looks cleaner that way so I decided to include it as well.
