### ISSUE TITLE
[BUG] old cert-manager api version on chart default

### ISSUE THREAD

**Issue by dominch** [Mailu/helm-charts#159]
**Describe the bug**
Recent versions of cert-manager removed old apis: cert-manager.io/v1alpha2 - it was replaced by v1 version. 
Right now default chart value uses old and unsupported api, this should be bumped to current version. 
Cert manager version can be passed as value: 
```
certmanager:
  apiVersion: cert-manager.io/v1
```
I think this value should be default instead of old v1alpha2 

**Environment**
k3s + mailu 0.2.0

**Comment by iptizer** [comment]
Is this something to be merged soon? Accidently upgraded cert-manager and now this chart no longer works...
