### ISSUE TITLE
[BUG] Redis fails to chown NFS volume

### ISSUE THREAD

**Issue by pixil98** [Mailu/helm-charts#163]
**Describe the bug**
When the Redis pod starts the first thing it does is try to chown it's filesystem. When using an NFS volume mount this fails and the pod terminates.

**Environment**
 - rke

**Additional context**
The solution to this is to use a securityContext to set the user and group that the pod is running as. Some of the pods in the Mailu helm chart allow a securityContext to be specified and some don't. Redis is one of the ones that doesn't.

**Comment by jonn1213** [comment]
Hi, so as I have an nfs mount I have mentioned problem. But I can't figur out how to use the containerSecurityContext option.
Thank you

**Comment by pixil98** [comment]
I ended up having more problems and didn't use Mailu. The crux of the problem I had was that I was mapping all access to the nfs drive to a non privileged user. When the container tried to chown the nfs directory, it would get an error. Ultimately I would have had to allow the container to access the nfs volume as root and it would have been allowed to chown the directory and presumably been happy.

**Comment by fastlorenzo** [comment]
Looks like a kubernetes volume management issue. You should try with release 1.0.0 of the chart which offers more configuration options.
