### ISSUE TITLE
Roudcube Fails to Recognise it has Started (Startup Probe) due to Curl Command Error

### ISSUE THREAD

**Issue by jamesarbrown** [Mailu/helm-charts#171]
1.9.20 Kubernetes reports Liveness probe failed: command "curl -f -L -H User-Agent: health http://localhost/" timed out

And I think thats the issue, as user-agent is not escaped as serial the space after _User-Agent:_ and before _health_ breaks the curl command

If i enter the pod and run curl with space removed
"curl -f -L -H User-Agent:health http://localhost/" 
its fine

Then i scalled down roundcube and edited the deployment to remove the space and scalled backup and all works now. This needs correcting in around line 120 of the template I believe.

**Comment by fastlorenzo** [comment]
The User-Agent parameter needs to be quoted with it's value otherwise -H parameter only take the first block before the space.

**Comment by fastlorenzo** [comment]
Fixed in release 1.0.0
