### ISSUE TITLE
Persistence size for each component

### ISSUE THREAD

**Issue by arturhefczyc** [Mailu/helm-charts#176]
**Is your feature request related to a problem? Please describe.**

It is not clear from the docs or `values.yaml` file how much space is needed for each component.
Persistence size for a `single_pvc=true` is set `100Gi`, which is fine as we have plenty of space that is needed for everything.

However, when we have `single_pvc=false` and set size individually for each component it is not clear how much space each component needs. Or what the space is actually used for by this specific component, therefore it is difficult to estimate necessary size.

The defaults are inconsistent. For example combined `rspamd_clamav_persistence` is set to `20Gi` where individual persistence for each of them is set to `1Gi` for rspamd and `2Gi` for clamav.

This may lead to lots of wasted space which is allocated to component but not really used.

**Describe the solution you'd like**

Correct me if I am wrong but it seems more reasonable settings for each component would be:

* **dovecot** - keeps all the email messages, space is needed as much as needed, depending on the size of users mailboxes, reasonable default anywhere between `25Gi - 100Gi`
* **admin** -  keeps configuration that is main server configuration, domains configuration, perhaps user accounts. Unless I am missing something, it should need no more than `1Gi`
* **redis** - cannot find any information on this. How much space can it possibly need. Any input on this would be appreciated
* **postfix** - as I understand it needs space for configuration and mail queues. Average email message is less than 1MB. Therefore, it seems like more than enough would be `2Gi`
* **rspamd** - not sure about space requirements but suggested `1Gi` seems low enough.
* **clamav** - again not sure how much is really needed but again suggested `2Gi` seems low enough
* **roundcube** - as I understand, it uses IMAP and does not store much of user's data itself. So the space requirements should be minimal, like `1Gi` maybe?
* **webdav** - usually you do not need a lot of space for webdav, I think a reasonable default would be `2Gi`
* **mysql** - from what I understand Mailu uses database only to store configuration for various components. This cannot easily grow to GBs of data. It seems like `1Gi` should be more than enough.
* **fetchmail** - fetchmail just retrieves messages from other servers and stores them to dovecot. It does not need a lot of space itself. It seems like `1Gi` should be good enough.

**Comment by fastlorenzo** [comment]
This should be better in release 1.0.0.
