### ISSUE TITLE
Mailu Logging and (Grafana) Dashboard Support

### ISSUE THREAD

**Issue by jamesarbrown** [Mailu/helm-charts#178]
**Is your feature request related to a problem? Please describe.**
Monitoring of Mailu via Elasticsearch so that it can be hooked upto Grafana or Kibana

**Describe the solution you'd like**
An additon to the chart to deploy a filebeat and logstash instance that will export to a Elasticsearch instance (Elasticsearch to be considered outside of scope.

Have already created full configmaps and deployment yaml files are here
[mailu-logging](https://github.com/jamesarbrown/mailu-logging)

And tested to work against this dashboard in Grafana [11293](https://grafana.com/grafana/dashboards/11293)

**Describe alternatives you've considered**
syslog, but I think that would mean changes to the orginal mailu-postifx container.

**Comment by fastlorenzo** [comment]
You should be able starting from release 1.0.0 to fine tune what you deploy with the chart, closing this one as not really part of Mailu.
If you need some fixes in the chart to meet your use case, don't hesitate to open a specific issue or better, a PR :)
