### ISSUE TITLE
Project donation

### ISSUE THREAD

**Issue by arturhefczyc** [Mailu/helm-charts#184]
I would like to give donation to the project, specifically to @micw developer who contributed so much to the project.

Is this project or project leaders accepting donations?

A while ago I opened #118 issue to sponsor a k8s guide to get fully installed and functional Mailu on k8s. Since I have completed the task myself, the bounty as not been paid. I would like to offer this bounty to the project instead, or project leader. @micw seems like a developer who contributed most to the project.

@micw if you with to accept this donation, please claim the bounty and I can close the issue and release bounty for you.

**Comment by micw** [comment]
Thank you very much. I accept the donation :-)

**Comment by arturhefczyc** [comment]
Follow the link: https://www.bountysource.com/issues/103130194-full-guide-on-how-to-deploy-mailu-on-k8s-sponsorship
and click on "Solve Issue". It should lead you through the process. Once you do it, I will get an email from them about your claim. I will need to "accept the solution" in order for the bounty to be paid.

To make sure, it is really you who claimed the bounty, please update this issue on github to let me know that you claimed the bounty.

**Comment by micw** [comment]
Had to cloade #118 to proceed on bountysouce

**Comment by arturhefczyc** [comment]
All done on my side, the bounty should be released to you, please confirm.

**Comment by micw** [comment]
Thank you again. Bountysource finally managed to transfer the money. They say that they payout every friday but delayed it until now (I wrote a bunch of emails and blamed them public on twitter when they did not react to increase the pressure a bit).

I find it great that you support Open-Source projects. Please consider to use a different platform next time. Besides the payout delay, they keep a significant amount of the bounty (150€ in this case) plus let the recipient pay the paypal fee (another 100€).

Kind regards,
Michael.

**Comment by arturhefczyc** [comment]
Hi, I am open to using different platforms but... what are the other options? Do you have any suggestions?
