### ISSUE TITLE
Access to rspamd overrides.d

### ISSUE THREAD

**Issue by jamesarbrown** [Mailu/helm-charts#186]
Be able to override rspamd etc /etc/rspamd/local/overrides.d

As explained here [https://mailu.io/1.9/antispam.html#how-can-i-block-emails-from-a-domain](url) 

Bit I can not find how to implement in mailu-helm
_Files in the /mailu/overrides/rspamd/ folder are mapped to /etc/rspamd/override.d. Create the file /mailu/overrides/rspamd/multimap.conf_ 

I think for helm we just need a PVC mapping for /etc/rspamd/local/overrides.d in addition to the maps.d existing override?

**Comment by micw** [comment]
I think so. For overrides in the chart we have a concept with partial implementation. Additional overrides needs to be added.

**Comment by fastlorenzo** [comment]
Should be possible now in release 1.0.0
