### ISSUE TITLE
[BUG] Missing namespaces "mailu-mailserver"

### ISSUE THREAD

**Issue by marcorocci** [Mailu/helm-charts#187]
**Describe the bug**
When trying to install i receive the error 
**Error: create: failed to create: namespaces "mailu-mailserver" not found**

**Environment**
 - elm3

**Comment by abs0lom** [comment]
Create the namespace before run the helm command :
```
kubectl create namespace mailu-mailserver
```
Or add the correct flag to allow helm to create the namespace :
```
helm install mailu mailu/mailu -n mailu-mailserver --values my-values-file.yaml   --create-namespace
```

Some documentation about namespaces : https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/

**Comment by fastlorenzo** [comment]
Closing as related to usage of Helm and not this chart.
