### ISSUE TITLE
[BUG] Missing volume "certs" : secret "mailu-certificates"

### ISSUE THREAD

**Issue by marcorocci** [Mailu/helm-charts#188]
**Describe the bug**
After the install, the front pod not start,
he say:
MountVolume.SetUp failed for volume "certs" : secret "mailu-certificates" not found

**Environment**
 - Kubernetes Platform

**Comment by abs0lom** [comment]
Are you using [Cert-Manager](https://cert-manager.io/) to generate certificates ? In that case, it is probably a certificate generation problem.

Can you show your Helm provided values ?

**Comment by DrBu7cher** [comment]
What would the required values be to autogenerate the secret with cert-manager?

**Comment by DrBu7cher** [comment]
I got it. It is created automatically, I only ran into a rate limit so the cert could not be issued.

**Comment by fastlorenzo** [comment]
Release 1.0.0 has better certificate handling which should fix this.
