### ISSUE TITLE
Change (rspamd) deployment name to match vainilla mailu / documentation

### ISSUE THREAD

**Issue by woj-tek** [Mailu/helm-charts#189]
(this is a followup from https://github.com/Mailu/Mailu/pull/2446, sort of FR, sort of discussion)

**Is your feature request related to a problem? Please describe.**
Currently helm chart specifies all names (deployment/service/pod) with `{{ include "mailu.fullname" . }}-` prefix, eg.: https://github.com/Mailu/helm-charts/blob/eccf0342c81609c9b770205eb12c02683396f93a/mailu/templates/rspamd.yaml#L10-L12

Which results in everything deployment with mailu helm chart to be named `mailu-*`. As deiscussed in linked issue, the motivation to do so may be to help organisation assets related to mailu, but because in k8s those names are used to connect to services, looking at the documentation (https://mailu.io/1.9/antispam.html?highlight=spam#can-i-learn-ham-spam-messages-from-an-already-existing-mailbox) one has to adjust commandline host from `antispam` to `mailu-rspamd`. It was suggested to unify naming across mailu deployment options (and bring it in line with documentation)

**Describe the solution you'd like**
One option would be to change Deployment name to `antispam`, but I'm not sure it wouldn't cause slight mess in k8s deployment (with multiple deployments in same namespace)

**Describe alternatives you've considered**
Adjusting mailu documentation, but it was rejected (see linked PR)

**Comment by fastlorenzo** [comment]
Once #193 is done, it would be easier to add an option for each component to override the service name in the Helm values.

**Comment by fastlorenzo** [comment]
Fixed in release 1.0.0
