### ISSUE TITLE
Hide client configuration other hostnames

### ISSUE THREAD

**Issue by dominch** [Mailu/helm-charts#194]
**Is your feature request related to a problem? Please describe.**
Recently upgraded mailu to curent version and default front has changed to mailu page with admin/webmail login. There is also page with client configuration. Page is available to clients without need to login. 
I Added several domains but would like to see only the one that was typed in address bar (or one default, but not others). 

**Describe the solution you'd like**
For me best option is to show only domain that was typed in address bar, ie: mail.example.com => example.com 
If this is not possible then the domain configured as main

**Describe alternatives you've considered**
Because I don't want to easily spread information about all domains configured I needed to block this path on load balancer. 

**Additional context**
For me it was better to have roundcube straight on mail.example.com and admin on /admin address but I understand this direction.

**Comment by micw** [comment]
Hello,
Do you think this can be solved in the context of the helm chart or ingress? It looks to me like something that needs to be solved within mailu admin itself.

Kind regards,
Michael.

**Comment by dominch** [comment]
I was not sure if it's feature of mailu itself or helm packaging or if there is any option to turn this feature off just in helm vars. Do You think it's better to report it straight to mailu?

**Comment by fastlorenzo** [comment]
@dominch with the refactored version, you should be able to configure the paths / host you want to expose for the Ingress (see #193)

**Comment by fastlorenzo** [comment]
Fixed in 1.0.0

**Comment by dominch** [comment]
thanks for information,
meanwhile I needed to block that on load balancer (which is quite easy), let's upgrade it now  and see what is changed
