### ISSUE TITLE
Support for parent subPath with existingClaim

### ISSUE THREAD

**Issue by brettinternet** [Mailu/helm-charts#195]
**Describe the solution you'd like**
I reuse an existing claim from an NFS PV for various services and would like to specify a subPath for that claim. I realize the chart deploys various subpaths for each service already, but perhaps it could be possible to define an optional parent directory for the subpaths.

**Describe alternatives you've considered**
This may be a K8s anti-pattern, but I find it's appropriate for my simple home use in my small cluster. The practical alternative is to create a new claim pointed to the precise storage path.

Thank you for sharing this excellent project.

**Comment by fastlorenzo** [comment]
Fixed in 1.0.0
