### ISSUE TITLE
[BUG]2022-12-16 08:09:38 #9(controller) <ad1152>; csession; fuzzy_check_io_callback: got error on IO with server localhost:11335(127.0.0.1:11335), on read, 111, Connection refused

### ISSUE THREAD

**Issue by OLED1** [Mailu/helm-charts#199]
**Describe the bug**
Sometimes mail sending is not possible and needs to be restarted because of the following rspamd error:
2022-12-16 08:09:38 #9(controller) <ad1152>; csession; fuzzy_check_io_callback: got error on IO with server localhost:11335(127.0.0.1:11335), on read, 111, Connection refused

Another error message compareable to the above one in my log is:
rspamd_inet_address_connect: connect [::1]:11335 failed: 99, 'Address not available'

I checked if the port is open anyway and it turns out it's not:
```
rspamd:~# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:11334           0.0.0.0:*               LISTEN      1/sec ham; 2.41s av
tcp        0      0 0.0.0.0:11332           0.0.0.0:*               LISTEN      1/sec ham; 2.41s av
tcp        0      0 :::11334                :::*                    LISTEN      1/sec ham; 2.41s av
tcp        0      0 :::11332                :::*                    LISTEN      1/sec ham; 2.41s av
rspamd:~# curl localhost:11335
curl: (7) Failed to connect to localhost port 11335 after 0 ms: Connection refused
```

Am i doing something wrong?

**Environment**
 - Kubernetes v1.25.4
 - (Helm)App Version: 1.9
 - (Helm)Package Version: 0.3.3

**Additional context**
Because i am running some backup tools which are sending status mails which often can't be sent at the first try, i ask you for help. Thanks in advance.

**Comment by fastlorenzo** [comment]
Please try again with 1.0.0 and mailu 2.0.0. Re-open the issue if this is still happening
