### ISSUE TITLE
Add the ability to change replicas in values.yaml

### ISSUE THREAD

**Issue by OLED1** [Mailu/helm-charts#201]
**Is your feature request related to a problem? Please describe.**
I am running a multi node kubernetes cluster and expose the mailserver ports (smtp3, pop and imap) through the nodeport.
The Problem now is that i have to manually change the replica count to the count of my total worker nodes by editing the deployment config of the front. - But of course, this solution is not peristent.

**Describe the solution you'd like**
Please add the ability to change the replica count in the values.yaml file.

**Describe alternatives you've considered**
Manually change the replica count to the count of my total worker nodes by editing the deployment config of the front. 

**Additional context**
None.

**Comment by fastlorenzo** [comment]
Should be possible in 1.0.0
