### ISSUE TITLE
[BUG] YAML parse error on mailu/templates/admin.yaml

### ISSUE THREAD

**Issue by sayga231** [Mailu/helm-charts#202]
**Describe the bug**
YAML parse error on mailu/templates/admin.yaml: error converting YAML to JSON: yaml: line 90: found character that cannot start any token

**Environment**
 - MicroK8s

**Additional context**
Followed all steps for a simple install giving me the error for converting when I try to install.

**Comment by fastlorenzo** [comment]
Not enough information to reproduce.
Please try again with release 1.0.0 and re-open with more information if you still encounter the issue.
