### ISSUE TITLE
[BUG] Deployments fail with "Can't read SECRET_KEY"

### ISSUE THREAD

**Issue by iptizer** [Mailu/helm-charts#203]
**Describe the bug**

The deployments "front", "postfix" and "rspamd" fail with the following error:

```sh
ERROR:root:Can't read SECRET_KEY from file: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/config.py", line 8, in <module>
    system.set_env()
  File "/app/venv/lib/python3.10/site-packages/socrate/system.py", line 35, in set_env
    raise exc
  File "/app/venv/lib/python3.10/site-packages/socrate/system.py", line 32, in set_env
    secret_key = open(os.environ.get("SECRET_KEY_FILE"), "r").read().strip()
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

So they seem to be unable to read a env file called `SECRET_KEY`.

**Additional context**

I am using mailu with this helm chart for quite some time. I think for over 2 years now or so. To be honest, I am not sure why this has worked before (see below). Maybe there was a change in an unpinned upstream library.

I also see that in #143 the option for a secret reference was added, but not altered with the deployments I am receiving the error.

When checking for example the ["front" deployment](https://github.com/Mailu/helm-charts/blob/master/mailu/templates/front.yaml#L64-L122) there is simply no variable called `SECRET_KEY' as the above mentioned PR adds.

I was able to solve the problem by just adding the env variable manually to the respective deployments as follows:

```yaml
        - name: SECRET_KEY
          value: s3cr3tk3y
```

I am very happy to provide a PR here, but I simply do not understand why this has worked before and why no one else is having this problem. Maybe someone can provide some guidance?

**Environment**

Deployed on a k8s cluster which is deployed using [Kubespray](https://github.com/kubernetes-sigs/kubespray).

kubespray version: 2.20

mailu chart version: 0.3.3

k8s version: 1.22

**Comment by iptizer** [comment]
Issue found...

Giving a hint:

```yaml
# DO NOT USE MASTER!!!!
#mailuVersion: master
# DO NOT USE MASTER!!!
```

**Comment by Matthew-Beckett** [comment]
Not using master is not an option for ARM64 users, can a maintainer advise the solution for ARM users who've been using `master-arm` from Dockerhub?

Where can we pull ARM64 compatible images from?
