### ISSUE TITLE
`hostnames[0]` is used both for ingress and for SMTP HELO

### ISSUE THREAD

**Issue by roobre** [Mailu/helm-charts#204]
**Is your feature request related to a problem? Please describe.**

`hostnames[0]` is used, as reported [here](https://github.com/Mailu/Mailu/issues/2188#issuecomment-1021005089), to define the name that is used as SMTP HELO. This name is important as many mail servers do not like when it is different to the reverse record (PTR) of the IP address mailu uses.

However, on this chart, all `hostnames` are used to create ingresses. The effective implications of this is that, if one wants to have a `HELO` that resolves to the canonical name of an IP address, e.g. `mydomain.tld`, mailu will listen in the web root for that domain (`http://maildomain.tld`).

**Describe the solution you'd like**

I would prefer these two settings to be configurable separately. E.g., to have my mail interface served at `https://mail.domain.tld`, while being able to tell mailu to use a different domain (`domain.tld`) for SMTP HELO.

**Describe alternatives you've considered**

- Hacking an ingress out of the chart, which I'd rather not

**Additional context**

I would consider adding an `ingresses` entry in `values.yaml`, sibling to `hostnames`, that defults to an empty list `[]`. If `ingresses` is not empty, the chart would use it to generate ingresses with those hostnames instead of `hostnames`.

---

Edit: Apologies for the empty issue/incomplete title, I somehow pressed Ctrl-Enter by accident 😓

**Comment by fastlorenzo** [comment]
Fixed in 1.0.0

**Comment by roobre** [comment]
Hey @fastlorenzo, apologies for the late reply, I'm catching up on the latest mailu updates now. Could you clarify what is the current way to achieve this? I'm taking a look a the latest `values.yaml` and documentation but I'm not being able to figure out how.
