### ISSUE TITLE
[BUG] - Setting up using helm chart causes DNS Validation issue

### ISSUE THREAD

**Issue by entrymon** [Mailu/helm-charts#205]
**Describe the bug**
While using latest kubernetes i.e 1.25.x++ if you install mailu using helm chart, we noticed that one of pod does not spin up complaining DNS Issue

`CRITICAL:root:Your DNS resolver at 10.96.0.10 isn't doing DNSSEC validation;`

MailU refers to this as core DNS bug in FAQ - Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation.

**Environment**
 - Minikube Platform

**Additional context**
Core DNS has fixed the issue but the helm chart still does not work out of box 
- https://github.com/coredns/coredns/issues/5826
- https://github.com/Mailu/Mailu/pull/2253

**Comment by fastlorenzo** [comment]
Fixed in 1.0.0 and Mailu 2.0.0
