### ISSUE TITLE
[BUG] REAL_IP_FROM setted to trust the internet by default

### ISSUE THREAD

**Issue by migs35323** [Mailu/helm-charts#209]
**Describe the bug**

https://github.com/Mailu/Mailu/issues/2688

i used the official chart to deploy a mailu server, and my machine was tricked to bounce mails
I believe the default "REAL_IP_FROM" was the culprit but since my vps was shutted down by the provider due to the machine spamming mails i have no way to test it again.
the relevant settings that i used are in the original thread. i can provide more info if requested
I had fetchmail enabled (i seen there was a vulnerability that was patched) not sure if this is relevant

**Environment**
 - k3s 1.24.10
 - ubuntu host
 - mailuVersion: 1.9.50

**Comment by fastlorenzo** [comment]
fixed in https://github.com/fastlorenzo/helm-charts-1/pull/53

**Comment by fastlorenzo** [comment]
Can be set via `ingress.realIpFrom` value in 1.0.0
