### ISSUE TITLE
mailu trusts everything inside the cluster network by default

### ISSUE THREAD

**Issue by migs35323** [Mailu/helm-charts#210]
### Version

- mailu Version: `1.9.50`
- chart version: 0.3.3

## Description

I had been testing mailu in kubernetes for a couple weeks now and i had a first deployment that was taken over by a spam attack as one of my first experiences with mailu.
i want to make clear i have no previous experience with deploying a mail system, i had been working with k8s deployments and sometimes docker for a year, this was my first contact with a mail system.
In this thread i want to provide my own experience with mailu + kubernetes with all the info i could gather to help mailu's deployment or other users.

## my hardware setup:

k3s 1.24 cluster with several nodes
every node is a vps hosted in a provider each with it's own public ip
using default klipper load balancer as it doesn't require a dedicated ip for the LB

## Protip (more like noob tip)

just one little hint, if anyone is having issues with the mail being flagged as spam these tools helped a lot with the troubleshooting of dmarq dkim headers and whatnot:
https://mha.azurewebsites.net/
https://testconnectivity.microsoft.com/
https://mxtoolbox.com/ (found in the mailu docs)

## The thread

so, i had been testing mailu for a couple of weeks and one of my first setup ended up almost costing the ban of 1 VPS machine due to being acted as an open relay after a lot of investigation i believe i finally can tell my conclusion.

So, i deployed mailu and even tough i followed all the docs and helm chart, i was victim of a particular setup

in my first trials with dmarq and dkim enties, my mail was exiting from the machine where the pods where scheduled, so in this first setup after a little of troubleshooting i figured out that i should use one node machine as the "mail machine"
so i had a node selector and everything cool like the "LOCAL" flag to make sure that incoming and outgoing mails where going only trough one machine (so, it is like using docker and not taking advantage of the HA or cool kubernetes stuff)
So i always made tests to know if i was open relay and it was OK they showed up as not a relay
HOWEVER, as i had setup the external ports as a LOAD BALANCER, (so external traffic policy flag was LOCAL) this opened up the load balancer in all the nodes and traffic could enter trough other nodes, 
theese other nodes where forwarding the traffic into mailu and BOOM, mailu assumes traffic from theese other nodes was internal traffic!

so, inside a mailu container it sees no difference between traffic from a mailu related pod, a random pod, a node, and in this my previous case from any internet traffic...

SO MAKE SURE THAT WHEN DEPLOYING IN K8S, THE TRAFFIC COMING FROM OTHER NODES IS NOT BEING FORWARD TO ANOTHER MACHINE

By default from the host machine or from a pod in the cluster, (even other namespaces), telnet into the pods port 25 it will assume i am trusted since it believes the traffic is from inside the cluster
maybe i am missing something? there are probably network policy rules that could be implemented by default so only mailu pods are able to talk with each other

There is a pod CIDR flag but this in kubernetes doesn't translate well... in the docker compose the default is to create a whole network dedicated to mailu containers, in kubernetes a pod cidr is the cluster-wide network.. it should give an hint about the network but shouldn't rely on it for security.

there is also another note, from what i had seen i believe mailu is a "designed for docker" "app", the chart doesn't take advantage of any stuff like config maps or secrets that kubernetes offers, 
still, i want to say really thank you for the helm chart, they take a lot of work and make life to users much easier

**Comment by micw** [comment]
Hello,

thank you for reporting this. There is one thing I do not understand. With "external traffic policy = local" kubernetes forwards traffic to local nodes only (which is AFAIK the only way to preserve the original remote IP address on TCP level). So a request sent to a different node should be go to nowhere.
The behaviour is very clear specified in https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip

So either you setup was missing something to really use "external traffic policy = local" or something does not behave as it is specified.

What is you exact setup (LoadBalancer, Kubernetes engine etc.)?

**Comment by migs35323** [comment]
i was using k3s version v1.24.10+k3s1 with the default klipper LB (load balancer built in the k3s)
there was an update a few days ago which pratically fixes this issue, i was using k3s for a long time and only a few days ago they fixed it, sadly it was after i tried mailu in my first test trials
https://github.com/k3s-io/k3s/releases/tag/v1.24.11%2Bk3s1
versions before this update EVEN WITH THE LOCAL policy, will accept and foward traffic into other machines.
https://github.com/k3s-io/k3s/pull/6908

but still. this is valid for people who didn't update or are using other Load balancer which might be accepting traffic into another machine

**Comment by micw** [comment]
I see, thank you for clarification.
Thats a very unfortunate issue with k3s and I think we should add some warning in the docs.

However, I can see no way for mailu to separate between wanted and unwanted internal traffic. The service needs to be available to internal requests and trust the requests (that's by design of mailu). So if a request appears internal, it is trusted automatically.

Maybe we should mirror the services (especially nginx) so that one for internal and one for external exists. This way the external could trust no one and only the internal could be used for trusted access.

**Comment by fastlorenzo** [comment]
Release 1.0.0 allows to use network policies, this should allow more flexibility in filtering traffic.
