### ISSUE TITLE
Redis Sentinel & authentication & perhaps even TLS

### ISSUE THREAD

**Issue by D1StrX** [Mailu/helm-charts#237]
**Is your feature request related to a problem? Please describe.**
New to Mailu, but looking at the Helm chart it doesn't seem to support Redis sentinels, external secret reference for DB password or TLS. Is this really the case? Also using Bitnami Redis Helm chart.

**Describe the solution you'd like**
- External Redis existing secret reference to the DB password (Must have)
- Redis Sentinel support (Nice to have)
- TLS support (Should have)

**Additional context**
![image](https://user-images.githubusercontent.com/40062371/232600818-933c3798-f88e-456f-b640-944f6c61cc55.png)

**Comment by fastlorenzo** [comment]
Thanks for your idea, the issue with external redis is that the mailu containers using redis don't support authentication. If you'd like to have this supported, the best place is to join the Mailu matrix room or open an issue in the main Mailu repo.

**Comment by D1StrX** [comment]
https://github.com/Mailu/Mailu/issues/2780
