### ISSUE TITLE
Allow choose certmanager api version

### ISSUE THREAD

**Issue by omitrowski** [Mailu/helm-charts#24]
in `https://github.com/Mailu/helm-charts/blob/master/mailu/templates/certificate.yaml` the `apiVersion: cert-manager.io/v1alpha2` is used, that is depricated in newer k8s versions. E.g. in k8s v1.16.x using cert-manager v 0.9.x the new version `certificates.k8s.io/v1beta1` is used.

**Comment by omitrowski** [comment]
it tuns out `cert-manager.io/v1alpha2` is the newer, and there is even `cert-manager.io/v1alpha3`  comming.

**Comment by micw** [comment]
Fixed with 1bd971ba3bc90082f9f798b6cfee4a56ea3f5f23
