### ISSUE TITLE
Add possibility to set securityContext option in Dovecot container

### ISSUE THREAD

**Issue by ffdfgdfg** [Mailu/helm-charts#240]
**Describe the bug**
https://github.com/Mailu/Mailu/issues/1714

I add the `SYS_CHROOT` in dovecot deployment, web mail works normal.
Hope add this option to charts!

**Environment**
 - Kubernetes Platform [Baremental, 1.26, cri-o]

**Additional context**

**Comment by zozo6015** [comment]
I am facing this issue. Could you please elaborate the code exactly where I need to add this to the dovecot deployment? I have tried to add it but does not seam to have any kind of effect. That is why I am thinking that I am not doing something right.

**Comment by zozo6015** [comment]
I can confirm it's working. Thank you
