### ISSUE TITLE
Add `proxyAuth` section to values to configure `PROXY_AUTH_*` env vars

### ISSUE THREAD

**Issue by lorenzo-w** [Mailu/helm-charts#247]
**Is your feature request related to a problem? Please describe.**

It is currently not straightfoward to add [proxy header authentication](https://mailu.io/master/configuration.html#header-authentication-using-an-external-proxy) to the Mailu instance deployed with this chart, as the associated env vars are hardcoded to disable the feature here:

https://github.com/Mailu/helm-charts/blob/2a8eed8da871b1a2ec35675885e854e9fe6158c9/mailu/templates/envvars-configmap.yaml#L64

**Describe the solution you'd like**

I propose adding a new section to `values.yaml` called `proxyAuth` and dynamically setting the env vars from the values there.

**Describe alternatives you've considered**

I've considered adding the Mailu env vars manually via `extraEnvVars`, yet it was unclear on which deployment to add them (front, admin, webmail?). Only through experimentation I found out what to do. Adding a dedicated, documented section to values seems more usable and more in line with the general approach of this chart.

**Comment by fastlorenzo** [comment]
agreed, and thanks for the PR, that would indeed simplify usage
