### ISSUE TITLE
Optionally expose prometheus metrics via ServiceMonitors

### ISSUE THREAD

**Issue by mrueg** [Mailu/helm-charts#254]
**Is your feature request related to a problem? Please describe.**
Currently there's no good way to see if the services mailu is composed of behave well.

**Describe the solution you'd like**
[Prometheus](https://prometheus.io) is a monitoring system that a lot of Kubernetes users use.
[Prometheus-Operator](https://github.com/prometheus-operator/prometheus-operator) provides CRDs (ServiceMonitors) that allow to automatically discover metric endpoints and have them scraped by Prometheus.

**Describe alternatives you've considered**
* Labels on Services

**Additional context**
None

**Comment by fastlorenzo** [comment]
@mrueg Prometheus metrics is something that would need to be exposed by Mailu itself through an endpoint.
There is not much we can do from the Helm Chart point of view, I suggest you check this issue: https://github.com/Mailu/Mailu/issues/1059

I'll close this for now until this is sorted in Mailu.

**Comment by mrueg** [comment]
@fastlorenzo could they be exposed already for the services mailu uses?

Rspamd exports them via /metrics endpoint: https://rspamd.com/doc/workers/controller.html / https://github.com/rspamd/rspamd/pull/3754#issuecomment-843258322
Dovecot would allow the same with some more configuration here: https://doc.dovecot.org/configuration_manual/stats/openmetrics/
