### ISSUE TITLE
[BUG] Error: secret "mailu-roundcube" not found when "webmail.enabled" is false

### ISSUE THREAD

**Issue by abs0lom** [Mailu/helm-charts#259]
When you want to deploy the chart without roundcube, the secret "mailu-roundcube" is not created (which seems normal to me). Nevertheless, it is referenced in the template below, which uses it to create an environment variable, which makes the deployment fail :

https://github.com/Mailu/helm-charts/blob/56002c67f790a10a5b5a67ea4543d4632d879fba/mailu/templates/_secrets.tpl#L71-L75

Also, other environment variables referencing roundcube are listed in the CM, even though they don't interfere with the deployment :

https://github.com/Mailu/helm-charts/blob/56002c67f790a10a5b5a67ea4543d4632d879fba/mailu/templates/envvars-configmap.yaml#L76

https://github.com/Mailu/helm-charts/blob/56002c67f790a10a5b5a67ea4543d4632d879fba/mailu/templates/envvars-configmap.yaml#L108-L112

I will propose a PR on this subject this weekend

**Comment by fastlorenzo** [comment]
Thanks for the report and PR, let me check this
