### ISSUE TITLE
front.externalServices with type=NodePort broken

### ISSUE THREAD

**Issue by redimp** [Mailu/helm-charts#268]
When configuring the `front.externalServices` with `type=NodePort`
```yaml
front:
  externalService:
    enabled: true
    type: NodePort
``` 

You run into
```
Error: UPGRADE FAILED: cannot patch "mailu-front-ext" with kind Service: 
Service "mailu-front-ext" is invalid: spec.ports[0].nodePort: 
Invalid value: 995: provided port is not in the valid range. 
The range of valid ports is 30000-32767
```

My guess is, that in https://github.com/Mailu/helm-charts/blob/master/mailu/templates/front/service-external.yaml#L38
the `nodePort` was configured by mistake when `targetPort` was meant.

Proposed fix (just an example, necessary to be updated for all ports)
```
       {{ if eq $.Values.front.externalService.type "NodePort" -}}
-      nodePort: 995
+      targetPort: 995
       {{- end }}
```

Tested it locally and it works as intended.

Happy to create a pull request.

**Comment by redimp** [comment]
After rereading this: @StopDenBus is right. Not a bug.

**Comment by ccbur** [comment]
I think this is still a bug. Changing the nodeport range is very unusual and not possible in some environments like AWS EKS (see https://github.com/aws/containers-roadmap/issues/1361).

**Comment by bidord** [comment]
I agree with @ccbur: changing the `--service-node-port-range` flag to restricted port numbers (meaning < 1024) is both:
- not allowed on many cloud providers
- a bad practice that could stop your whole cluster from working properly

This Helm chart should let sysadmins customize nodePorts numbers and their default values should be within the default range 30000-32767.
