### ISSUE TITLE
mailu postfix cannot start and when it does, cannot send or receive email

### ISSUE THREAD

**Issue by mamiapatrick** [Mailu/helm-charts#27]
Hello,
i use this chart to install mailuserver and installation seems to go well as every pods starts and proceeed installation at the beginning. Now i'm facing severals issues 
- mailupostfix cannot start with an error `Mar 24 10:06:29 mail postfix/postfix-script[55]: fatal: the Postfix mail system is already running`
- when i log in roundcube, roundcube cannot send mail (error 220 authentication) and cannot retrieve mail for a user i got these kind of error

`imap(admin@xxxxx.com)<41270><1v184pah3qgKKgtQ>: Error: chdir(/mail/admin@xxxxx.com) failed: Stale file handle

Mar 24 10:05:00 imap(admin@xxxxx.com)<41268><wox74pah3KgKKgtQ>: Info: Logged out in=102 out=888 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0

Mar 24 10:05:00 imap(admin@xxxxx.com)<41270><1v184pah3qgKKgtQ>: Error: stat(/mail/admin@xxxxx.com/tmp) failed: Invalid argument

Mar 24 10:05:01 imap(admin@xxxxx.com)<41270><1v184pah3qgKKgtQ>: Error: stat(/mail/admin@xxxxx.com/tmp) failed: Invalid argument

Mar 24 10:05:01 imap(admin@xxxxx.com)<41270><1v184pah3qgKKgtQ>: Error: stat(/mail/admin@sxxxxx.com) failed: Stale file handle

Mar 24 10:05:01 imap(admin@xxxxx.com)<41270><1v184pah3qgKKgtQ>: Error: stat(/mail) failed: Stale file handle

Mar 24 10:05:01 imap(admin@xxxxx.com)<41270><1v184pah3qgKKgtQ>: Error: opendir(/mail/admin@xxxxx.com) failed: Stale file handle

Mar 24 10:05:01 imap(admin@xxxxx.com)<41270><1v184pah3qgKKgtQ>: Error: Failed to get quota resource STORAGE: quota-count: Listing namespace '' failed: opendir(/mail/admin@xxxxx.com) failed: Stale file handle

Mar 24 10:05:01 imap(admin@xxxxx.com)<41270><1v184pah3qgKKgtQ>: Info: Logged out in=114 out=820 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0

Mar 24 10:05:06 auth: Debug: auth client connected (pid=41279)`

Is it normal that the volumemount are so different with the version of mailuserver that are in the kubernetes documentation [here](https://github.com/Mailu/Mailu/tree/1.7/docs/kubernetes/mailu).

For example in the helm chart the volume for data is in the subpath "dovecotdata" while in the kubernetes docs the volume is mount at the same subpath with the other pods as mail-admin etc ... 
the volumes for this chart are very different from documentation while it's seems to be the same images.

I think for example that these error on IMAP are caused by these mismatch on dovecot volumes, in chart the subpath for mail is dovecotmail while in [mailu kubernetes doc](https://github.com/Mailu/Mailu/blob/1.7/docs/kubernetes/mailu/imap.yaml) is "mailstate". Please do someone have mailuserver working correctly with this chart. How to configure it? Thanks

**Comment by micw** [comment]
Hello,
the k8s docs are from 1.7 and are a bit outdated. I have used them as reference for the helm chart but many things have changed since then.
Do you use the "master" images for your deployment? The 1.7 version had lots of issues on k8s, the master hast appropriate patches. 1.8 will be the 1st stable version that should run flawlessly on k8s.

**Comment by mamiapatrick** [comment]
Hello @micw 

Thanks you for your response! Yeah i use the "master" images for my deployment. Do you have some advices for the bugs that i previously mentionned ? Postfix is still crashing

**Comment by micw** [comment]
Actually no, I did clean-install it a few days ago on my test system without any issues. Please join us on "Mailu" in matrix chat, so we can see what's going wrong.

**Comment by mamiapatrick** [comment]
On this issue when i look into the pod, the process started at the launch of the post i saw that the entrypoint launch the script twice, once with the user root and another with the user postfix. Can it be the source of the bug?

`PID   USER     TIME  COMMAND
    1 root      0:00 {start.py} /usr/bin/python3 /start.py
    6 postfix   0:00 {start.py} /usr/bin/python3 /start.py
  305 root      0:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /b
  310 root      0:00 /bin/bash
  320 root      0:00 ps aux`

**Comment by alialshamali** [comment]
Hi,

I ran into the same postfix issue on a fresh install.
```
Apr 07 10:01:31 mail postfix[49]: Postfix is running with backwards-compatible default settings
Apr 07 10:01:31 mail postfix[49]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Apr 07 10:01:31 mail postfix[49]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
Apr 07 10:01:35 mail postfix/postfix-script[71]: fatal: the Postfix mail system is already running
```
also admin and roundcube also failing
```
mail-cloud-mailu-admin-b597d576f-4pn7s                       0/1     Running   14         81m
mail-cloud-mailu-clamav-57dddc6f96-q9959                     1/1     Running   0          81m
mail-cloud-mailu-dovecot-6dcbd5db46-6vzdt                    1/1     Running   0          81m
mail-cloud-mailu-front-dkm8m                                 1/1     Running   0          81m
mail-cloud-mailu-front-g7s2j                                 1/1     Running   0          81m
mail-cloud-mailu-front-hd52h                                 1/1     Running   0          81m
mail-cloud-mailu-front-r4lwv                                 1/1     Running   0          81m
mail-cloud-mailu-mysql-86476db78d-q4mm5                      1/1     Running   0          81m
mail-cloud-mailu-postfix-6cc446dbcd-6bchd                    0/1     Running   14         81m
mail-cloud-mailu-redis-7664dc578c-zstjc                      1/1     Running   0          81m
mail-cloud-mailu-roundcube-7d4c7c565f-dlmpj                  0/1     Running   17         81m
mail-cloud-mailu-rspamd-5c8459dddf-xxpmj                     1/1     Running   0          81m
mail-cloud-mailu-webdav-6f96644bdd-56vhq                     1/1     Running   0          81m
```

**Comment by micw** [comment]
Can you post the logs with DEBUG enabled?

**Comment by unixfox** [comment]
Maybe it's unrelated but this could solve some problems here.
There is a bug in mariadb docker image which hangs for a very long time until the real database gets setup: https://github.com/docker-library/mariadb/issues/262
If you see a bunch of `root unauthorized` errors in the pod of `mailu-mysql` then you encounter this bug.
What I did is to switch to this alternative image of mariadb which is also lighter thanks to alpine: https://hub.docker.com/r/yobasystems/alpine-mariadb

**Comment by micw** [comment]
Please provide further information, without I'll close the issue soon.

**Comment by micw** [comment]
Closing due to lack of response.
