### ISSUE TITLE
[BUG] mailu-dovecot requires permission changes to access /tmp/podop.socket

### ISSUE THREAD

**Issue by fiskhest** [Mailu/helm-charts#278]
**Describe the bug**
`mailu-dovecot` struggles to make the podop connection on startup. Logs report:
```
Jul 31 15:40:08 lmtp(10382): Info: Connect from 10.42.0.210
Jul 31 15:40:08 lmtp(admin@fiskhe.st)<10382><MAcdNbi5x2SOKAAA5u+K8g>: Error: sieve: dict storage: script `default': Failed to lookup script id from path priv/sieve/name/default: net_connect_unix(/tmp/podop.socket) failed: Permission denied (euid=1000(<unknown>) egid=1000(mailu) missing +w perm: /tmp/podop.socket, dir owned by 0:0 mode=0777) (reply took 0.000 secs (0.000 in dict wait, 0.000 in other ioloops, 0.000 in locks))
Jul 31 15:40:08 lmtp(admin@fiskhe.st)<10382><MAcdNbi5x2SOKAAA5u+K8g>: Error: sieve: Failed to access sieve_before script from `dict:proxy:/tmp/podop.socket:sieve' (temporary failure)
```

**Environment**
 - k3s

**Additional context**
I have a NFS volume mounted as a pvc, and thus have had to intervene with a couple of other specific uid/gid settings, see #277.
Whenever `mailu-dovecot` is restarted, I get these errors until I
`chmod 0777 /tmp/podop.socket`, which makes dovecot work normally until next restart.

**Comment by fiskhest** [comment]
For the time being, I've been able to work around this issue with a `kustomization` patch:

```
# patch-startup-permissions.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailu-dovecot
  namespace: mailu-mailserver
spec:
  template:
    spec:
      containers:
        - name: dovecot
          lifecycle:
            postStart:
              exec:
                command:
                - /bin/sh
                - -c
                - "sleep 10 && chmod 0777 /tmp/podop.socket"
```
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helm-generated.yaml

patches:
- path: patch-startup-permissions.yaml
```

**Comment by fastlorenzo** [comment]
I believe this is an issue with your storage setup, closing this except if you find a pattern, feel free then to re-open

**Comment by fiskhest** [comment]
Wouldnt be surprised if that was so - I will be rebuilding my cluster within not too long and am planning for a more robust storage solution. I will report back if I can get some more meaningful information out of the new setup.
