### ISSUE TITLE
Replace front daemonset with hostport by a front deployment with a service

### ISSUE THREAD

**Issue by rouja** [Mailu/helm-charts#28]
Hi,

In kubernetes, a daemonset is an object to deploy a specific pod on all nodes or a set of nodes. I think it's a cluster admin object. Here, the chart uses a daemonset to expose a pod outside the cluster. I think it's probably not the better way to achieve it. 
I think that replace the daemonset by a deployment and use a service to expose what we need outside the cluster should be better. Actually it will probably be more secure too. 
For instance, I'm not sure that theses ports need to be exposed on the WAN :
```
          - name: smtp-auth
            containerPort: 10025
            hostPort: 10025
            protocol: TCP
          - name: imap-auth
            containerPort: 10143
            hostPort: 10143
            protocol: TCP
```

I think a good example of what I mean can be found here [here](https://github.com/Zempashi/docker-jitsi-meet/tree/k8s-helm/examples/helm).

**Comment by micw** [comment]
Hi,
daemonset vs. deployment has nothing to do with security, it's just a definition of how many are deployed (deployments have a fixed number of instances, daemonsets have one per node).
I just copied it from https://github.com/Mailu/Mailu/blob/master/docs/kubernetes/mailu/front.yaml and did not see that there's a daemonset. Deployment makes indeed more sense.

Regarding the ports, I need to check if they are needed for something.

**Comment by rouja** [comment]
Hi,

As you said "daemonset vs. deployment has nothing to do with security" and my issue mixes two distinct things. Maybe it's better to split it into two issues ?

As far as I know, 10025 and 10143 are not "public e-mail" ports. I think theses ports are used in private by some components (probably dovecot and postfix to check users for instance).

**Comment by micw** [comment]
Hi,
It's both fixed now.

**Comment by briantopping** [comment]
Thank you! :) https://github.com/Mailu/Mailu/pull/576#discussion_r226570980
