### ISSUE TITLE
[BUG] Postfix liveness probe is not sufficient to detect faulty pods

### ISSUE THREAD

**Issue by ArnCo** [Mailu/helm-charts#282]
**Describe the bug**
In both of my clusters, postfix does not answer to RCPT TO after a few days of normal operation. Deleting the faulty pod solves the problem.

**Environment**
 - K3S + Rancher - Single node

**Additional context**
For some reason, postfix crashes after a while, but the crash is not detected by the liveness probe, as the server answers normally to the ```echo QUIT|nc localhost 25|grep "220 .* ESMTP Postfix"``` command.

However, comparing the processes in a faulty pod vs a working one, it is noticeable than most of them have been killed:

1. Pod working
```
  11 postfix   0:08 python3 /start.py
   12 postfix   0:57 python3 /start.py
  274 root      0:00 {postfix-script} /bin/sh /usr/libexec/postfix/postfix-script start-fg
  341 root      0:04 /usr/libexec/postfix/master -s
  343 postfix   0:00 qmgr -l -t unix -u
23455 postfix   0:00 tlsmgr -l -t unix -u
225227 postfix   0:00 postlogd -l -n postlog -t unix-dgram -u
263828 postfix   0:00 pickup -l -t unix -u
265535 postfix   0:00 smtpd -n smtp -t inet -u -o stress= -s 2
265573 postfix   0:00 anvil -l -t unix -u
265585 postfix   0:00 smtpd -n smtp -t inet -u -o stress= -s 2
265986 root      0:00 grep postfix
```

2. Pod not working
```
   11 postfix   0:04 python3 /start.py
   12 postfix   0:54 python3 /start.py
  304 root      0:00 {postfix-script} /bin/sh /usr/libexec/postfix/postfix-script start-fg
  371 root      0:04 /usr/libexec/postfix/master -s
 4949 postfix   0:00 tlsmgr -l -t unix -u
102206 postfix   0:03 postlogd -l -n postlog -t unix-dgram -u
307335 postfix   0:00 smtpd -n smtp -t inet -u -o stress= -s 2
308155 root      0:00 grep postfix
```

**Comment by ArnCo** [comment]
The reason of the postfix crash is most probably linked to my VPS being snapshoted by my hosting provider every night, which results in high IO load and restart of a few pods.
How could the liveness probe be improved for postfix ?

**Comment by fastlorenzo** [comment]
Thanks for the report, it looks like Mailu changed the healthcheck for Postfix https://github.com/Mailu/Mailu/blob/32d1c7d899e81d7de24f2e15cb39bf0eb298a2fe/core/postfix/Dockerfile#L18

I'll review all probes to make sure they're in line with Mailu upstream

**Comment by ArnCo** [comment]
Thank you so much for the quick PR, I'm testing it live right now :+1:

**Comment by ArnCo** [comment]
Well I have been testing your PR and the issue reoccured 3 days after the helm chart was upgraded. I am not sure how the  liveness probe could be modified in order to make it more reliable.

**Comment by fastlorenzo** [comment]
@ArnCo did you try to increase the probes timeout in the values.yaml file?
What's the exact error you get?

**Comment by ArnCo** [comment]
The problem is that the probe succeeds even if postfix is in an unstable state, as described [here](https://github.com/Mailu/helm-charts/issues/282#issue-1846397049).
Thus the pods is not restarted.

**Comment by fastlorenzo** [comment]
@ArnCo the PR uses the same healthcheck as in Mailu repo: https://github.com/Mailu/Mailu/blob/fb97cec2381d86555c25943495f8383c82564be3/core/postfix/Dockerfile#L18

If that healthcheck fails and is not correct, it is best to open an issue directly in Mailu repo to have it fixed upstream before we change it here.
