### ISSUE TITLE
Authentication failure with Roundcube

### ISSUE THREAD

**Issue by ndjido** [Mailu/helm-charts#29]
I am deploying Mailu v1.7 on a GKE cluster. The deployment went well but when it comes to login on portal I can notice 2 behaviors :
* when credentials is wrong it says so
* when it's corrects auth just fails with 401 error without any further details. 
I even set the log level to debug, it did not help.

**Comment by rouja** [comment]
Hi,

Did you turn off IMAP or POP3 like in this [issue](https://github.com/Mailu/Mailu/issues/1375) ?

**Comment by ndjido** [comment]
@rouja looks like the same issue. Is there a way to turn on IMAP or POP3 in the `value.yaml` ?

**Comment by micw** [comment]
Users reported issues with certain CNIs (i think with flanell with some specific option set), which one are you using?

**Comment by ndjido** [comment]
@micw I am using the GKE's native CNI

**Comment by ccbur** [comment]
I had the same problem today. Changing the subnet in the values.yaml solved it for me:

`subnet: 10.244.0.0/16
`

_10.244.0.0/16_ is often the pod subnet in a Kubernetes installation. I have no idea why _10.42.0.0/16_ is configured in the default values.yaml. Maybe a typo?

**Comment by micw** [comment]
Seems both are widely used. I think we should add a check and fail gracefully if it's set up wrong (I recall there's already an issue in mailu bug tracker)

**Comment by micw** [comment]
I have added a trouble shooting section to the README, describing that problem.

**Comment by micw** [comment]
@ndjido Sorry, saw that the solution was not posted by you when I closed this. Feel free to re-open if it does not fix the problem for you.
