### ISSUE TITLE
Re-add containerSecurityContext

### ISSUE THREAD

**Issue by solacelost** [Mailu/helm-charts#293]
**Is your feature request related to a problem? Please describe.**
Earlier versions of the charts supported setting containerSecurityContext on components, which helps with more restrictive Kubernetes platforms' default settings. I am currently unable to use the newer mailu charts on my cluster since [this PR](https://github.com/Mailu/helm-charts/pull/173) was not carried forward into the refactor.

**Describe the solution you'd like**
I'd like sensible contanerSecurityContext or pod-level securityContext options available in values.yaml.

**Describe alternatives you've considered**
Forking the charts and maintaining the patch set myself.

**Additional context**
You can see in mailu/templates/front.yaml (removed [here](https://github.com/Mailu/helm-charts/commit/f918c2cb5472169f0b1453ee2e75c55cc5cb5317)) that this option existed, and was not added back in the refactor - the same holds true for other components.

**Comment by fastlorenzo** [comment]
@solacelost thanks for the request, I believe #263 should fix this as well
