### ISSUE TITLE
[BUG] Postfix forward to Dovecot

### ISSUE THREAD

**Issue by mkshb** [Mailu/helm-charts#299]
**Describe the bug**
main.cf configuration virtual_transport value wrong

`Sep 13 09:00:08 mail postfix/lmtp[868]: EBDC120033: to=<mailadmin@xxx.de>, relay=none, delay=131, delays=0.78/0.07/130/0, dsn=4.4.1, status=deferred (connect to mailu-front.mailu.svc.cluster.local[x.x.x.x]:2525: Operation timed out)`

**Environment**
 - K3s on Cloud Hoster

**Additional context**
Postfix tries to forward messages to mailu-front.mailu.svc.cluster.local:2525 instead of mailu-dovecot.mailu.svc.cluster.local:2525

main.cf:
```
# Mails are transported if required, then forwarded to Dovecot for delivery
relay_domains = ${podop}transport
transport_maps = lmdb:/etc/postfix/transport.map, ${podop}transport
virtual_transport = lmtp:inet:mailu-front.mailu.svc.cluster.local:2525
```

Tried to fix it with an override in values.yaml without success.

```
  overrides:
    main.cf : |
      virtual_transport = lmtp:inet:mailu-dovecot.mailu.svc.cluster.local:2525
```

**Comment by kooskaspers** [comment]
which chart version are you using?

**Comment by mkshb** [comment]
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
mailu   mailu           9               2023-09-13 10:11:37.16900298 +0200 CEST deployed        mailu-1.4.0     2.0.22

**Comment by mkshb** [comment]
I temporarly solved it my setting an env var to the postfix pod.

```
extraEnvVars: 
    - name: FRONT_ADDRESS
      value: mailu-dovecot.mailu.svc.cluster.local
```
