### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zozo6015** [Mailu/helm-charts#308]
**Describe the bug**
After installing the Helm chart the command that shows how to get the admin password is wrong. It looks like 
```
kubectl --namespace=global get secrets get secrets mail-mailu-initial-account -o jsonpath='{.data.initial-account-password}' | base64 --decode
```

while it should be:
```
kubectl --namespace=global get secrets mail-mailu-initial-account -o jsonpath='{.data.initial-account-password}' | base64 --decode
```

**Environment**
 - Kubernetes Platform [e.g. GKE, Rancher2, ...]
Managed OVH k8s platform

**Comment by christf** [comment]
for me this is 

`
 kubectl --namespace=default get secrets mailu-initial-account -o jsonpath='{.data.initial-account-password}' | base64 --decode
`
