### ISSUE TITLE
[BUG] Default configuration disables outbound TLS of Postfix

### ISSUE THREAD

**Issue by Birkenstab** [Mailu/helm-charts#319]
## Description:
Using the default values in values.yaml results in TLS being disabled for outbound SMTP connections of Postfix.

Default value of tls.inboundEnforce in values.yaml does not result in the default value of OUTBOUND_TLS_LEVEL environment variable of Mailu being used.

This is because:
* [values.yaml](https://github.com/Mailu/helm-charts/blob/master/mailu/values.yaml#L237C5-L237C5) default value for the tls.outboundLevel is:
  ```yaml
  tls:
    outboundLevel: ""
  ```

* This causes the environment variable `OUTBOUND_TLS_LEVEL` to be set to `""` by [the config map](https://github.com/mailu/helm-charts/blob/master/mailu/templates/envvars-configmap.yaml#L64):
  ```OUTBOUND_TLS_LEVEL: {{ .Values.tls.outboundLevel | quote }}```

* This causes the configuration value `smtp_tls_security_level` of Postfix to be set to `""` instead of the default value `"dane"` in the [Mailu Postfix Config](https://github.com/nextgens/Mailu/blob/master/core/postfix/conf/main.cf#L58):
  ```smtp_tls_security_level = {{ OUTBOUND_TLS_LEVEL|default('dane') }}```
  The default value would have been used if the environment variable was unset instead of an empty string.

* This causes Postfix to  set `smtp_tls_security_level` to `none`. This disables TLS for outbound SMTP connections. This causes Postfix to send all emails in unencrypted clear text. See [Postfix Config Doc](https://www.postfix.org/postconf.5.html#smtp_tls_security_level)

## Possible solutions:
1. Set values.yaml `tls.outboundLevel` to the default which is `dane`. Drawback: If Mailu changes its default, it needs to be updated here too.
2. Set `tls.outboundLevel` to `null`. I am not sure if this will work and cause the environment variable `OUTBOUND_TLS_LEVEL` to be unset.

**Comment by dlford** [comment]
@fastlorenzo this is still an issue, looks like an easy one for me to get started on if that's alright?
