### ISSUE TITLE
Unable to mount volumes for pod

### ISSUE THREAD

**Issue by andrewnazarov** [Mailu/helm-charts#32]
Deploying this to GKE with standard storage class users might face an issue with volumes like the following:
```
Unable to mount volumes for pod "mailu-postfix-7779bbcb88-4rvzm_mailu(b7dab7b3-42b1-4fb0-8e87-539ca7b04539)"
```
`RollingUpdate` will also fail because of that.

Probably this worth being mentioned in the readme as a warning or a solution could be provided.

**Comment by micw** [comment]
Can you please give more detail, what exactly fails?
Are you deploying to multiple nodes? If so, you need to set "persistence.accessMode" to "ReadWriteMany".
I'll update the doc.

**Comment by micw** [comment]
Docs are updates. If there are no further concerns, I'll close the issue.

**Comment by andrewnazarov** [comment]
Yeah, I'm ok with it. There is a different task for further work: https://github.com/Mailu/helm-charts/issues/39
