### ISSUE TITLE
Please add an option to disable rspamd

### ISSUE THREAD

**Issue by gomin1d** [Mailu/helm-charts#339]
**Is your feature request related to a problem? Please describe.**
There is no easy way to disable rspamd.

**Describe the solution you'd like**
I want `rspamd.enabled: false` option.

**Describe alternatives you've considered**
.

**Additional context**
I have run mailu for the prometheus alertmanager alert system. Only sending outgoing emails. Recipients - several administrators. I don't want the rspamd antispam system. And letters from prometheus are very similar to each other, so they are blocked by the rspamd system.

**Comment by gomin1d** [comment]
up

**Comment by gomin1d** [comment]
up

**Comment by fastlorenzo** [comment]
Closed in #337

**Comment by gomin1d** [comment]
> Closed in #337

COOL
