### ISSUE TITLE
Setting up Ingress or Service with loadBalancerIp for front service

### ISSUE THREAD

**Issue by briantopping** [Mailu/helm-charts#34]
It's not very clear how to best set up an ingress for the Helm chart. The main site documents how to use Kubernetes, but these generated manifests are different enough that those instructions aren't usable. It is tricky because `loadBalancerIp`s need to be configured and those IPs may overlap with the service. Services furthermore may not be able to share an IP address with nginx, adding another wrinkle.

**Comment by micw** [comment]
I fear I don't understand the question...
"Creating an ingress" usually means "adding an ingress resource" - and there's one in the chart already. What does it have to do with loadBalancerIp?

**Comment by briantopping** [comment]
Oops, I forgot I filed this. I think I am going to look at #35 as the fix for this. 👍
