### ISSUE TITLE
Provide an Helm-Value to add extraContainers for each component

### ISSUE THREAD

**Issue by hans-fischer** [Mailu/helm-charts#343]
**Is your feature request related to a problem? Please describe.**
I realy want to have metrics about the mailu-installation. I know you guys dont provide the containers but there are ways to archive metrics over sidecar containers.
Some of them just bind to the socket of the server e.g. postfix-unixsocket or dovecot-unixsocket.

Postfix: https://github.com/kumina/postfix_exporter
Dovecot: https://github.com/kumina/dovecot_exporter

With the ability to add sidecar-containers to different pods I could mount the socket into the sidecar an provide metrics about mailu-components without touching/destroying the rest of your very good work.

**Describe the solution you'd like**
It would be nice if I could just throw in the definition of a sidecar container and deploy it along with yout helm chart. Another possible usage for sidecars could be a backup container using a backup-solution like restic to backup all mailboxes to an s3 bucket.

**Describe alternatives you've considered**
Use custom containers that provide metrics about the mailu-app without adding extra Containers but that would mean a lot of maintainance.

**Comment by fastlorenzo** [comment]
closed in #344
