### ISSUE TITLE
"Unable to attach or mount volumes" on Multi Host Cluster

### ISSUE THREAD

**Issue by christian98** [Mailu/helm-charts#36]
Hello everyone,

Yesterday I tried to install the mailu Chart in my Cluster (currently 1 master, 2 nodes). The installation works just fine, but three pods are stuck in "ContainerCreating"-Status. The problem seems related to the mounting/binding of the storage pv. (For info, I use openebs as the storage provider).

I think the problem is that the chart only uses one pvc for all storage and all pods are mounting this one storage. But my pods are scheduled on different hosts so only the pods on one host can access the storage. All pods on the other host can not access it, because the other host is using the volume obviously..

![grafik](https://user-images.githubusercontent.com/26673604/79949596-13b72b00-8476-11ea-8f3c-06f89753a57b.png)

Maybe a solution is to use multiple pvc's? or some sort of affinity to place them all on the same host? Or is there a more simple solution?

I'm barely new to the Kubernetes terminology, sorry for that :-)

**Comment by micw** [comment]
Hi,
you can either use persistence with ReadWriteMany (https://github.com/Mailu/helm-charts/blob/master/mailu/values.yaml#L43 - if your storage supports it) or use a node selector to bind all pods on one node: https://github.com/Mailu/helm-charts/blob/master/mailu/values.yaml#L24

Multiple PVs would also work but are currently not supported by the chart.

**Comment by christian98** [comment]
Hey,
the "ReadWriteMany"-Suggestion was great. I set up NFS-Storage with Openebs and now everything works just fine.

The NodeSelector was no option for me, because i want k8s to schedule the pods to nodes and don't have to move NodeLabels. I think pinning services to one node is a bit against the concepts of k8s.

But anyway, Thanks for your help!
