### ISSUE TITLE
Rename smtps to submissions

### ISSUE THREAD

**Issue by fastlorenzo** [Mailu/helm-charts#364]
**Is your feature request related to a problem? Please describe.**
The protocol for port `465` is Submission and not SMTP.

**Describe the solution you'd like**
Replace `smtps` with `submissions` in  https://github.com/Mailu/helm-charts/blob/cfc2b7bf2425ac6e05574da48ee13b29b0307d32/mailu/values.yaml#L628
and
https://github.com/Mailu/helm-charts/blob/cfc2b7bf2425ac6e05574da48ee13b29b0307d32/mailu/values.yaml#L687
Make sure it stays backward compatible by supporting `smtps` until the next major release.

**Describe alternatives you've considered**
N/A

**Additional context**
https://datatracker.ietf.org/doc/html/rfc8314#section-7.3

**Comment by WebSpider** [comment]
@fastlorenzo anything else that needs to be done to the PR?
