### ISSUE TITLE
[BUG] "UID SEARCH: Internal error occurred"

### ISSUE THREAD

**Issue by chris2k20** [Mailu/helm-charts#367]
**Describe the bug**
When attempting to search for any email within the webmail interface of Mailu, an error occurs with the message: "UID SEARCH: Internal error occurred. Refer to server log for more information." This issue persists for every search query across different mailboxes.

**Environment**
Mailu Version: latest
Kubernetes Platform: k3s
Database: PostgreSQL Bitnami
Resources: Many

**Additional context**
The error message indicates a possible internal issue during the UID search process.
![image](https://github.com/user-attachments/assets/22aaffe8-e089-40a8-8365-a154858574f7)

Thank you for the time you put into this project.

**Comment by WebSpider** [comment]
Can you see if there is any useful information in the imap container logs?

**Comment by chris2k20** [comment]
Working again... I don't know why. 
But thx for your help @WebSpider  :)
