### ISSUE TITLE
[BUG] Submission port 587 cannot be enabled with hostPort only

### ISSUE THREAD

**Issue by Vilsol** [Mailu/helm-charts#370]
**Describe the bug**
There is currently no way to enable submission port 587 when using only hostport without any ingress or services.

**Environment**
 - Bare metal v1.28.3

**Additional context**
The `PORTS` variable does not get set, but that is the only way how to enable the port 587.

I think the culprit lies in https://github.com/Mailu/helm-charts/blob/master/mailu/templates/_services.tpl#L171

Alternative solution would be allowing manually overriding the PORTS variable

My current workaround is to manually add the `PORTS` after deploying.

**Comment by vanthome** [comment]
@same issue here.
