### ISSUE TITLE
[BUG] Password modified via Admin/CLI, but authentication fail on other services

### ISSUE THREAD

**Issue by Arrogance** [Mailu/helm-charts#377]
**Describe the bug**
The authentication works against Admin. I can change there the password, and also via flask on admin pod, with no error, but when I try to access other services like the webmail, dovecot... I get:

dovecot:
```Disconnected: Connection closed (auth failed, 1 attempts in 2 secs): user=<user@domain.tdl>```

front:
```
Oct 22 17:58:20 imap-login: Info: proxy(user@domain.tdl,ipaddr:143): Login failed: [AUTHENTICATIONFAILED] Authentication failed.: user=<user@domain.tdl>, method=PLAIN, rip=ipaddr, rport=35160, lip=ipaddr, lport=10143, TLS
Oct 22 17:58:20 imap-login: Info: Disconnected: Connection closed (proxy dest auth failed): user=<user@domain.tdl>, method=PLAIN, rip=ipaddr, rport=35160, lip=ipaddr, lport=10143, TLS
```

Same if I try to connect to rspamd or webmail. Only the log in on admin works.

**Environment**
 - microk8s

**Additional context**
I upgraded to 2024.06.24 for fixing https://github.com/Mailu/Mailu/issues/3607

Also, all PVC uses independent NFS PV:
![firefox_79GVHwwjw6](https://github.com/user-attachments/assets/04737ea3-4ed2-44f4-b977-0a742ea91442)

**Comment by Arrogance** [comment]
It seems that even checking the mail server on external tools, and no errors about it, is because ports are blocked. I close this ticket and sorry about the issue.

**Comment by Arrogance** [comment]
I reopen because it was not the ports.

I've checked dovecot manually, inside the pod, to auth and I get this error:

```
passdb: admin@mail.facilitra.com auth failed
extra fields:
  user=admin@mail.com
```

I try to call the podot socket
```
mailu-dovecot-5698d668f-2qg4x:/app# curl --unix-socket /tmp/podop.socket http://localhost/auth/passdb/admin@mail.facilitra.com
curl: (52) Empty reply from server
```

I really don't know what's happening, after a few reinstall and different configs, even from NFS to local hostPath.

**Comment by IslamHeggy** [comment]
I faced the same issue and looks like I wasn't adding the proper subnet so all the components weren't working as expected!
@Arrogance

**Comment by Arrogance** [comment]
Yep, that was the issue. I realized after 20 reinstall or so...
