### ISSUE TITLE
Expand nodeSelector to other components

### ISSUE THREAD

**Issue by unixfox** [Mailu/helm-charts#38]
Currently, nodeSelector is only applied on the front component. 
It would be great to have the ability to force the others components on a specific node.

My use case is that when using [longhorn I can't mount the mailu-storage pvc on every pod if they are spread on multiple nodes at the same time](https://github.com/longhorn/longhorn/issues/73#issuecomment-537169134).

**Comment by unixfox** [comment]
Fixed in https://github.com/Mailu/helm-charts/commit/7e22c8358bb5db13a8c2a5c752d5e45e73892bdb

**Comment by micw** [comment]
Hehe, did not even had the time to close this issue before you found my fix ;-)
