### ISSUE TITLE
[BUG] Probes are not working

### ISSUE THREAD

**Issue by Sacerdoss** [Mailu/helm-charts#385]
**Describe the bug**
Probes for the front container are checking dovecot master pid in `/run/dovecot` with `kill -0` but this file is unlikely to exist in that container because dovecot runs in its own container

**Environment**
 - kubeadm v1.29.11

**Comment by fastlorenzo** [comment]
Thanks for your comment, but dovecot actually runs in this container as well, as can be checked in: https://github.com/Mailu/Mailu/blob/af017047c4811d1da9657ada6063bd207ef34a5f/core/nginx/start.py#L21

Closing this one, if you encounter an issue with running the front container, please provide more information (logs, env, etc.) so we can help resolving it.
