### ISSUE TITLE
[BUG] Multiattach Error

### ISSUE THREAD

**Issue by huang-jy** [Mailu/helm-charts#50]
**Describe the bug**
Pods will not come good due to multi-attach errors

**Environment**
GKE

**Additional context**
Attempting to set this up on a dev cluster using this:

```
helm upgrade \
  --install --wait --atomic \
  --namespace mailu \
  mailu mailu/mailu \
   --set hostnames={mail.domain.net} \
   --set domain=domain.net \
   --set ingress.tlsFlavor=letsencrypt \
   --set initialAccount.username=admin \
   --set initialAccount.domain=domain.net \
   --set initialAccount.password=XXXXX \
   --set secretKey=XXXXX \
   --set subnet=172.16.0.0/12 \
   --set certmanager.issuerType=ClusterIssuer \
   --set certmanager.issuerName=letsencrypt-production
```

The chart installs, but timeout due to this:

```
Multi-Attach error for volume "pvc-01188ee8-96be-11ea-897a-42010a9a00e6" Volume is already used by pod(s) mailu-admin-76f5b54765-cs8kt, mailu-postfix-546cdf5ff7-5t89f
```

Those pods never come good, helm times out on the wait and purges the chart as it did not install successfully

**Comment by micw** [comment]
Hello,
you need to set persistence.accessMode to ReadWriteMany (see https://github.com/Mailu/helm-charts/blob/master/mailu/README.md#pvc-with-automatic-provisioning) if you run on multiple nodes (and probably also for some PV implementations on one node).

There's currently only one PV that's shared across pods (see also #39).

**Comment by huang-jy** [comment]
Unless I'm missing something, you can't multi attach unless the underlying storage supports it. On GKE, the standard persistent disk doesn't support RWM, and this is confirmed by the following:

```
$ kubectl describe pvc -n mailu
Name:          mailu-storage
Namespace:     mailu
StorageClass:  standard
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    mailu-admin-76f5b54765-r2wkf
               mailu-clamav-5bf6cfc979-kzz4n
               mailu-dovecot-f94fc97bd-4448h
               mailu-postfix-546cdf5ff7-lsbqc
               mailu-redis-65ff5c674d-9q78m
               mailu-roundcube-59b654c6c8-8nvtc
               mailu-rspamd-c8ffb6647-cj2l9
Events:
  Type     Reason              Age               From                         Message
  ----     ------              ----              ----                         -------
  Warning  ProvisioningFailed  7s (x4 over 38s)  persistentvolume-controller  Failed to provision volume with StorageClass "standard": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce 
ReadOnlyMany] are supported

```

**Comment by micw** [comment]
According to https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes, there is only a limitation on how many nodes a storage can be mounted. So it should be allowed to attach a volume to more than one pod (even with ReadWriteOnce if pods run on one node).
See also https://stackoverflow.com/questions/56592929/how-pods-are-able-to-mount-the-same-pvc-with-readwriteonce-access-mode-when-stor and https://github.com/kubernetes/kubernetes/issues/60903 for discussion around this. But that's not an issue of this particular helm chart.

For this chart are 2 solutions: use a storage provider that supports mounting to many pods (or ReadWriteMany if you want to run on multiple nodes. Or wait for #39 to be implemented (PRs are very welcome).

You also can ask for help in the "mailu" matrix channel, I'm pretty sure there are some users running on GKE.

**Comment by huang-jy** [comment]
I managed to resolve the multiattach by using this guide to create a RWM pvc and then referenced that using `--set persistence.existingClaim`

I have a different question now. The services that come up are all `ClusterIP` type services, and the `mailu-front` is the only one that is linked via the ingress to the outside world. Unless I am mistaken, there's no way to allow the `postfix` service to be accessed from outside the cluster (ref: https://github.com/Mailu/helm-charts/blob/master/mailu/templates/postfix.yaml).

Is this intentional?

**Comment by micw** [comment]
Yes, nginx proxies everything and also does auth for mail protocols. Other services must not be exposed (since they are not secured)

**Comment by huang-jy** [comment]
Perfect, thank you :+1:

**Comment by huang-jy** [comment]
@micw just on your last comment (https://github.com/Mailu/helm-charts/issues/50#issuecomment-629624353), what should I make public if I wanted to make mailu available to receive emails from the world as an MX server?

I took a guess and mapped my ingress controller to route ports 110, 995, etc. directly to the `front` service. Is this the correct endpoint, since you mentioned Nginx does the auth for the protocols, and I'm guessing thats in here?

**Comment by micw** [comment]
"front" is nginx. That's the one that needs to be exposed. See the "hostPort" directives in the front pod which ports are exposed.
If you cannot use "hostPort" (I guess you cannot on GKE), you need to exposie it in a different way, usually through a load balance. I'm not familar with GKE, so I cannot tell how exactly it must be done. It probably needs change to the chart, I'm open for suggestions (there was already a feature request which was closed due to lack of feedback).

*Important!* If you expose the ports with other than "hostPort", you need to ensure that the *originating ip address* is passed down to nginx. Otherwise you will create an open relay that will be blacklisted within hours.
