### ISSUE TITLE
Allow option to specify relay method via SMTPD/SMTPS port instead of straight SMTP

### ISSUE THREAD

**Issue by huang-jy** [Mailu/helm-charts#52]
**Is your feature request related to a problem? Please describe.**
On Google Compute engine, Google blocks outbound port 25 traffic, but does allow SMTPD/SMTPS traffic. Postfix attempts to use port 25 to relay out, and cannot as a result. GKE runs on top of GCE so is subject to the same blocking.

**Describe the solution you'd like**
An option in the chart to tell mailu to relay out via SMTPD or SMTPS instead of straight SMTP.

**Describe alternatives you've considered**
None available

**Additional context**
Reference: https://cloud.google.com/compute/docs/tutorials/sending-mail/

**Comment by micw** [comment]
What is a use case for a mail server that cannot do outbound to port 25? Most mail servers out there won't accept unauthenticated traffic on the "alternative" ports like 587 or 465. Also see https://stackoverflow.com/questions/41179258/how-to-enable-smtp-port-25-in-google-cloud-redhat-7-instance for an in-detail discussion.

Besides that, support in mailu will be needed before such a feature could be added to the chart.

**Comment by huang-jy** [comment]
Yep. I'll leave this here and I'll look to see where else I can deploy this except for GKE. So for now, deploying mailu on GKE is a no-go unless you're only handling internal mail.

**Comment by micw** [comment]
Closing (we cannot fix if the cloud provider blocks port 25)
