### ISSUE TITLE
postfix crashes

### ISSUE THREAD

**Issue by justinasjaronis** [Mailu/helm-charts#53]
**Describe the bug**

After running some time (2-3 hours) postfix crashes abruptly. My PVC  has been set up on NFS  and I believe most probably it's issue with filesystem handing.

ay 21 11:30:18 mail3 postfix/smtpd[10793]: connect from localhost[127.0.0.1]
May 21 11:30:18 mail3 postfix/smtpd[10793]: disconnect from localhost[127.0.0.1] quit=1 commands=1
May 21 11:30:21 mail3 postfix/smtpd[10793]: connect from localhost[127.0.0.1]
May 21 11:30:21 mail3 postfix/smtpd[10793]: disconnect from localhost[127.0.0.1] quit=1 commands=1
May 21 11:30:28 mail3 postfix/smtpd[10793]: connect from localhost[127.0.0.1]
May 21 11:30:28 mail3 postfix/smtpd[10793]: disconnect from localhost[127.0.0.1] quit=1 commands=1
May 21 11:30:31 mail3 postfix/smtpd[10793]: connect from localhost[127.0.0.1]
May 21 11:30:31 mail3 postfix/smtpd[10793]: disconnect from localhost[127.0.0.1] quit=1 commands=1
May 21 11:30:38 mail3 postfix/smtpd[10793]: connect from localhost[127.0.0.1]
May 21 11:30:38 mail3 postfix/smtpd[10793]: disconnect from localhost[127.0.0.1] quit=1 commands=1
May 21 11:30:41 mail3 postfix/smtpd[10793]: connect from localhost[127.0.0.1]
May 21 11:30:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:30:41 mail3 postfix/smtpd[10793]: disconnect from localhost[127.0.0.1] quit=1 commands=1
May 21 11:30:48 mail3 postfix/smtpd[10793]: connect from localhost[127.0.0.1]
May 21 11:30:48 mail3 postfix/smtpd[10793]: disconnect from localhost[127.0.0.1] quit=1 commands=1
May 21 11:30:51 mail3 postfix/smtpd[10793]: connect from localhost[127.0.0.1]
May 21 11:30:51 mail3 postfix/smtpd[10793]: disconnect from localhost[127.0.0.1] quit=1 commands=1
May 21 11:30:58 mail3 postfix/smtpd[10793]: connect from 10-244-1-73.mail-ballancer.mail.svc.cluster.local[10.244.1.73]
May 21 11:30:58 mail3 postfix/smtpd[10793]: warning: connect #1 to subsystem private/rewrite: Invalid argument
May 21 11:31:08 mail3 postfix/smtpd[10793]: warning: connect #2 to subsystem private/rewrite: Invalid argument
May 21 11:31:18 mail3 postfix/smtpd[10793]: warning: connect #3 to subsystem private/rewrite: Invalid argument
May 21 11:31:28 mail3 postfix/smtpd[10793]: warning: connect #4 to subsystem private/rewrite: Invalid argument
May 21 11:31:38 mail3 postfix/smtpd[10793]: warning: connect #5 to subsystem private/rewrite: Invalid argument
May 21 11:31:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:31:48 mail3 postfix/smtpd[10793]: warning: connect #6 to subsystem private/rewrite: Invalid argument
May 21 11:31:58 mail3 postfix/smtpd[10793]: warning: connect #7 to subsystem private/rewrite: Invalid argument
May 21 11:32:08 mail3 postfix/smtpd[10793]: warning: connect #8 to subsystem private/rewrite: Invalid argument
May 21 11:32:18 mail3 postfix/smtpd[10793]: warning: connect #9 to subsystem private/rewrite: Invalid argument
May 21 11:32:28 mail3 postfix/smtpd[10793]: warning: connect #10 to subsystem private/rewrite: Invalid argument
May 21 11:32:38 mail3 postfix/smtpd[10793]: fatal: connect #11 to subsystem private/rewrite: Invalid argument
May 21 11:32:39 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 10793 exit status 1
May 21 11:32:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service qmgr(public/qmgr): Invalid argument
May 21 11:32:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:32:42 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11029 exit status 1
May 21 11:32:42 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 11:33:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:34:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:35:23 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11038 exit status 1
May 21 11:35:23 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 11:35:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:36:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:37:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service qmgr(public/qmgr): Invalid argument
May 21 11:37:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:38:04 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11039 exit status 1
May 21 11:38:04 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 11:38:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:39:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:40:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:40:45 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11040 exit status 1
May 21 11:40:45 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 11:41:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:42:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service qmgr(public/qmgr): Invalid argument
May 21 11:42:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:43:26 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11041 exit status 1
May 21 11:43:26 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 11:43:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:44:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:45:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:46:07 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11042 exit status 1
May 21 11:46:07 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 11:46:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:47:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service qmgr(public/qmgr): Invalid argument
May 21 11:47:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:48:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:48:48 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11060 exit status 1
May 21 11:48:48 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 11:49:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:50:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:51:29 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11061 exit status 1
May 21 11:51:29 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 11:51:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:52:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service qmgr(public/qmgr): Invalid argument
May 21 11:52:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:53:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:54:10 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11062 exit status 1
May 21 11:54:10 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 11:54:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:55:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:56:42 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:56:51 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11063 exit status 1
May 21 11:56:51 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 11:57:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service tlsmgr(private/tlsmgr): Invalid argument
May 21 11:57:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service qmgr(public/qmgr): Invalid argument
May 21 11:57:42 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:58:42 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 11:59:32 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11064 exit status 1
May 21 11:59:32 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 11:59:42 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 12:00:42 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 12:01:42 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 12:02:13 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11065 exit status 1
May 21 12:02:13 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 12:02:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service qmgr(public/qmgr): Invalid argument
May 21 12:02:42 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 12:03:42 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 12:04:41 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11083 exit status 1
May 21 12:04:41 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 12:04:42 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 12:04:54 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11084 exit status 1
May 21 12:04:54 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 12:05:42 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 12:06:42 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 12:07:22 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11085 exit status 1
May 21 12:07:22 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 12:07:35 mail3 postfix/master[352]: warning: process /usr/libexec/postfix/smtpd pid 11086 exit status 1
May 21 12:07:35 mail3 postfix/master[352]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
May 21 12:07:41 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service qmgr(public/qmgr): Invalid argument
May 21 12:07:42 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argument
May 21 12:08:42 mail3 postfix/master[352]: warning: master_wakeup_timer_event: service pickup(public/pickup): Invalid argumen

**Environment**
Digital Ocean
ReadWriteMany PVC on NFS 

**Additional context**

**Comment by micw** [comment]
Hello,
please use this tracker only for helm chart related issues. If there are any issues with mailu images, you can post to https://github.com/Mailu/Mailu

**Comment by justinasjaronis** [comment]
This problem is about postfix running on ReadWriteMany volume on NFS storage class. I mounted /queue as separate, independent ReadWriteOnce do-block-storage volume and issue seems to be solved. I don't understand what is the rationale of mounting /queue from main volume? Besides complexity of file locking etc, I am sure it wouldn't allow to scale postfix instances to a number more than one.

Also I know that dovecot running on NFS ReadWriteMany volume has to be configured accordingly: https://wiki2.dovecot.org/NFS However I didn't experience corruption there yet.

As with your current volume layout storage volume has to be used in ReadWriteMany mode, and with most cloud providers only choice is NFS, so I think that chart should transparently handle the configuration for this setup.

**Comment by micw** [comment]
Your questions to the volume are already covered in https://github.com/Mailu/helm-charts/issues/39 . The NFS stuff for dovecot is also documented in mailu docs and there's a pending issue here: https://github.com/Mailu/helm-charts/issues/22 .

**Comment by justinasjaronis** [comment]
I think this issue will be solved with #39 , so now I close the issue. I don't see any crashes when running on individual PVCs.
