### ISSUE TITLE
[BUG] Documentation about sample load balancer

### ISSUE THREAD

**Issue by justinasjaronis** [Mailu/helm-charts#56]
Currently this helm chart does not include load balancer. In such environments as Digital Ocean this setup is unusable.

Even more important, documentation must provide information to apply externalTrafficPolicy: Local otherwise newly set up cluster will be open relay. It is documented https://github.com/Mailu/Mailu/issues/1370 however I believe it should be solved in helm chart as well.

**Comment by micw** [comment]
One possible solution for some cloud providers (Digital Ocean?) is described in https://github.com/Mailu/Mailu/issues/1370#issuecomment-612439037

**Comment by justinasjaronis** [comment]
You are right, it does not show real sender IP address. But in my case (kubernetes 1.17.5) emails from outside originate from other subnet than local services and at least solves open relay issue.

**Comment by micw** [comment]
It breaks rate limits as well as spam detection and the opportunity to detect where a mail originated.

**Comment by micw** [comment]
A propper solution would be to use proxy protocol (https://www.digitalocean.com/docs/kubernetes/how-to/configure-load-balancers/#proxy-protocol) - but unfortunately nginx mail proxy modules does not support it

**Comment by WebSpider** [comment]
@micw the nginx mail proxy modules don't, but postfix itself does support it, for instance by including in the configuration `postscreen_upstream_proxy_protocol=haproxy`, combined with a suitable ingress config.

For nginx-ingress, an example would be

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  "25": "mail/mail-mailu-postfix:25::PROXY"
```
  
Granted, this is only a partial solution, since it would bypass the front service completely, which may cause other issues

**Comment by fastlorenzo** [comment]
Possible in release 1.0.0
