### ISSUE TITLE
Allow choosing between separate env vars or a single ConfigMap

### ISSUE THREAD

**Issue by frgomes** [Mailu/helm-charts#59]
**Is your feature request related to a problem? Please describe.**

For reasons which would be off-topic and TL;DR here, I prefer a single ConfigMap instead of environment variables specified individually in each containers. 

**Describe the solution you'd like**

I would like to have the ability to generate a configuration employing a single ConfigMap.

**Describe alternatives you've considered**

Generate a template .yaml, editing by hand and saving it in a safe place for regular use in my platform. This is not really an option, since I would not easily capture upstream improvements.

**Additional context**

The ability to restart containers when a ConfigMap changes ... or not having this ability at all... is not a concern to me, since from my experience, the more resilient approach at this point would be restarting the entire thing anyway.

I admit that in future I may eventually change my opinion on that. In this case, the thread below provides some ideas:

 * https://stackoverflow.com/questions/37317003/restart-pods-when-configmap-updates-in-kubernetes

Also, this matter is expected to be better addressed at some point in future:
* https://github.com/kubernetes/kubernetes/issues/22368

**Comment by frgomes** [comment]
I'm working on this issue. I'm basically shoving virtually all env vars into a single ConfigMap.

I've noticed that there are inconsistencies between the way several variables are defined. This may be  a source of bugs or troubles. I cannot positively affirm that bugs or troubles are caused by these discrepancies, though.

Having virtually all configurations defined in a single place adds consistency to the entire solution.

**Comment by micw** [comment]
Please add a list of inconsistencies so that I can check it.

**Comment by micw** [comment]
@frgomes Are you still interested to this? If so, please tell me about the inconsistencies you found - I think we first need to fix this prior to merge the PR.

**Comment by frgomes** [comment]
@micw
I cannot remember anymore the details involved here.
No, I'm not going to work on this direction for the foreseeable future.

**Comment by micw** [comment]
Closing due to lack of a stakeholder.
