### ISSUE TITLE
[RSPAMD] make configs in /etc/rspamd/local.d/ configurable

### ISSUE THREAD

**Issue by omitrowski** [Mailu/helm-charts#61]
### Use case: I wan to make custom entries in
- `history_redis.conf`, eg increase the history size according to https://rspamd.com/doc/modules/history_redis.html
- whitelists as described in https://gist.github.com/ThomasLeister/f41adad98bb46d0c8418de50b5efb4a0

### Possible solution: 
in `https://github.com/Mailu/helm-charts/blob/master/mailu/templates/rspamd.yaml` it could be easy to implement the possibility to mount extra drives in order to overwrite config files via configMap. As the `start.py` does use templates the right folder to mount the configMap files would be `/conf/`

- The configMap copuld look like:

```
{{- if .Values.rspamd.customConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-rspamd-customConfigMap
data:
# /etc/local.d/
{{- range $cfgName, $cfgContent := .Values.rspamd.customConfig.localD }}
  {{ $cfgName }} : |-
{{ $cfgContent | indent 4 }}
{{- end }}
{{- end }}
```

- accordingly the `rspamd.yaml` like:

```
          volumeMounts:
{{- range $cfgName, $cfgContent := .Values.rspamd.customConfig.localD }}
            - name: customConfig
              mountPath: "/conf/{{ $cfgName }}"
              subPath: {{ $cfgName }}
{{- end }}
...
      volumes:
...
{{- if .Values.rspamd.customConfig.localD }}
        - name: customConfig
          configMap:
            name: {{ template "app.name" . }}-rspamd-customConfigMap
            items:
{{- range $cfgName, $cfgContent := .Values.rspamd.customConfig.localD }}
              - key: {{ $cfgName }}
                path: {{ $cfgName }}
{{- end }}
{{- end }}
```
- and the values.yml:

```
rspamd:
  customConfig:
    localD:
      history_redis.conf: |-
        servers = "\{{ REDIS_ADDRESS \}}";
        nrows = 2000;
        compress = true;
        subject_privacy = false;
```

**Comment by omitrowski** [comment]
we are going to provide a PR for this.

**Comment by omitrowski** [comment]
To me it looks compatible to https://github.com/Mailu/helm-charts/pull/60

**Comment by micw** [comment]
Is this still of interest? Souldn't we use the override mechanism here?
