### ISSUE TITLE
Rancher 2 and helm chart incompatibillity?

### ISSUE THREAD

**Issue by Devineavenger** [Mailu/helm-charts#79]
**Describe the bug**
 Deploying a new app "mailu" version 0.1.0 from the rancher catalog.
After setting up all the variables and hitting deploy, I get the following error

Wait helm template failed. Error: template: mailu/templates/ingress.yaml:20:17: executing "mailu/templates/ingress.yaml" at <.Values.hostnames>: range can't iterate over [subdomain.domain.tld] Use --debug flag to render out invalid YAML : exit status 1

I am at a loss, as far as i can tell, it's a syntax error

Not an expert programmer, need help diving deeper into the problem

**Environment**
 - Rancher 2.5.3

**Additional context**

**Comment by dnauck** [comment]
The old Rancher Apps feature had a lot of issues with 3rd party helm charts. But if you try out the new `Cluster Explorer -> Apps & Marketplace` helm3 feature you'll have success.

I'm using Rancher 2.5.7

**Comment by Devineavenger** [comment]
What old rancher app? As stated above, I'm on rancher 2.5.3....

**Comment by dnauck** [comment]
Old (Cluster Manager):
![image](https://user-images.githubusercontent.com/97584/112734332-5ebea580-8f45-11eb-847c-512b1f479f86.png)

New (Cluster Explorer - New Dashboard):
![image](https://user-images.githubusercontent.com/97584/112734341-6da55800-8f45-11eb-903b-8be1f04cdc93.png)

**Comment by micw** [comment]
@Devineavenger Does this fix it or you?

**Comment by Devineavenger** [comment]
Sorry, after many nights I deemed it was not production worthy, went with a separate bare metal and docker install... I was hard pressed for time... I didn't have the time to fiddle with things... Probably when they decide on something that works (old/new/newer/whatever) I'll give it another go. Right now, there are too many variables and as time goes on, I'm finding myself relying less and less on rancher and deploying more with manifests... Since then, I've set up 2 more clusters and none of them have any connection with rancher... Can't find the spare resources (neither bare metal/vm nor time) to go into helm right now...
