### ISSUE TITLE
Deployment Specs Missing Selector

### ISSUE THREAD

**Issue by denebeim** [Mailu/helm-charts#8]
I'm a helm newbie, however when I tried to deploy this chart it wouldn't install and intellij seems to agree, that there needs to be a selector in the spec portions of the deployment yamls.
If that's not the case let me know.  Otherwise here's a pull request.

**Comment by micw** [comment]
Hello,
you are right, the selectors are missing. For some reason I was able to deploy multtiple times without. Probably the selectors are only enforced on recent kubernetes versions.

**Comment by micw** [comment]
Closed by https://github.com/Mailu/helm-charts/commit/c4f1e1626e54b35ef6ac634d141a01b74bcf1bd7
