### ISSUE TITLE
Is this GIT repository still maintained?

### ISSUE THREAD

**Issue by berni2288** [Mailu/helm-charts#87]
Hey there,

is this GIT repository still maintained?

I was thinking about creating pull requests here, but I don't want to waste my time if this GIT repo is not maintained anymore.
The reason why I'm asking is because there are some PRs that are already almost a year open.

If this is not maintained anymore I'll just continue to use my fork.

Thanks!

**Comment by micw** [comment]
Hello,
maintainer here. Technically, it is ;-)
Unfortunately, due to lack of time (new job, lockdown with home schooling), I was not able to review PRs in the last few months. Any help with this would be highly appreciated.

Kind regards,
Michael.

**Comment by berni2288** [comment]
Hey Michael,

no problem, can I help you somehow?
I'm not tracking the latest development progress of mailu, but I have some good knowledge about writing charts and Kubernetes.
Let me know!

Regards,
Bernhard

**Comment by micw** [comment]
Mailu came to new life with a new team. They started a monthly meeting where I try to participate and I also try to spend at least an evening per month in reviewing PRs. Hope that counts as "is maintained" ;-)
