### ISSUE TITLE
[BUG] Preserve antispam history on container restart

### ISSUE THREAD

**Issue by Diman0** [Mailu/helm-charts#95]
**Describe the bug**
See [issue #561](https://github.com/Mailu/Mailu/issues/561) in the mailu repo. On container recreating/restart the rspamd logs are lost. The reason for this is that rspamd stores the logs in redis with a key that contains the hostname.

On recreating/restart of the container the hostname changes of the antispam container and for this reason the old logs cannot be retrieved. 

The solution is to configure a static hostname for the antispam container. I have no knowledge of kubernetes or helm-charts. Looking at the files I think in this file can be configured that the antispam (rspamd) container uses a static hostname:
https://github.com/Mailu/helm-charts/blob/master/mailu/templates/rspamd.yaml

For docker-compose you can use
```
antispam:
  hostname: rspamd
  image: mailu/rspamd:$VERSION
  restart: always
```
I reckon you can do something similar for helm-charts.

**Comment by micw** [comment]
Thank you. It's solved by setting a fixed hostname
