### ISSUE TITLE
[feature] Support for handling multiple mail domains

### ISSUE THREAD

**Issue by huang-jy** [Mailu/helm-charts#96]
**Is your feature request related to a problem? Please describe.**
Not an existing problem

**Describe the solution you'd like**
I think it would be worthwhile to have a mailu Helm installation be able to support multiple mail domains.

At the moment, it appears the helm chart only supports a single mail domain, which is fine for the majority of users, but I manage three domains, each with the possibility of having their own emails.

I would have to deploy three copies of mailu to cover this scenario and configure three installations and make sure they are in sync.

Having a single installation would allow anyone in a similar scenario to myself to only have to configure one installation.

Yes, there are inherent downsides and risk to this such as a single point of failure -- if the one installation goes down, all three mail domains go down, but there is also the easier management for things like security -- you only have to patch one installation or upgrade one installation rather than three and risk forgetting to do one.

**Describe alternatives you've considered**
Multiple installations of mailu, each configured for its own separate domain

**Additional context**
N/A

**Comment by micw** [comment]
Mailu does support multiple mail domains in any configuration (including the helm chart). The domain you configure is just the MTA hostname which has to be a unique one (e.g. mail.mydomain.com). In the admin UI you can add as many domains as you want.
If that answers your question, please close the issue. If not, let me know.

**Comment by huang-jy** [comment]
Is that configurable via the helm chart, though? There's a value for
domain, but I figured it only takes one domain?

**Comment by micw** [comment]
> The domain you configure is just the MTA hostname which has to be a unique one (e.g. mail.mydomain.com)

**Comment by huang-jy** [comment]
Thanks, let me do some more tinkering and I'l close this ticket if I can
get it working.

Thanks for the reply.

**Comment by huang-jy** [comment]
All good, did the testing and seems to work. I'll close this issue.
